earthobservations/wetterdienst

example/python_dwd_example.ipynb, python_dwd/file_path_handling/file_list_creation.py, tests/additionals/test_functions.py, tests/file_path_handling/test_file_list_creation.py
@gutzbenj 
run tests with `pytest tests/`
I will configure the repo that this is done automatically and merge is only possible when all tests passed.
=> Add first tests, and small refactoring

python_dwd/additionals/helpers.py
renamed ftp function to read file into bytes like object
=> Small issue with function name fixed

README.md, python_dwd/additionals/functions.py, requirements.txt, tests/additionals/test_functions.py
@gutzbenj 
I hope you like my refactoring. Should be faster and easier to understand
=> Lighter and faster File 2 parameter/timeResolution mapping

python_dwd/additionals/geo_location.py, python_dwd/data_collection.py, python_dwd/file_path_handling/file_list_creation.py, python_dwd/metadata_dwd.py
Dear @gutzbenj I implemented what I have mentioned in chat.  You can now parse a string according to the enum. 
And I added a small feature to the get_nearest_station function
=> Enable to parse string and not only enumeration to functions.

python_dwd/dwd_station_request.py
I added a method to collect data for a defined request. The method is build as generator so that you can do the following:
`
for df in request.collect_data(...):
`
The method currently handles all parameters for the data interaction with the hard drive. 
Besides the added method I also changed the parameter parsing based on the enumeration abilities @meteoDaniel added for the other functions.
=> Add method to get data for a defined station request

DWD_FTP_STRUCTURE.md, Dockerfile, README.md, python_dwd/data_collection.py, python_dwd/enumerations/period_type_enumeration.py, python_dwd/run.py, requirements.txt, tests/test_dwd_station_request.py
I have enhanced the docker support and enabled the `collect_dwd_data` to run as script to download the data. 
And I have added a table of availabilities. 
And please take care of tests in your future PR's. Thanks ;)
=> Add docker support and run script

.github/workflows/main.yml
This is a first guess of github actions running our tests with docker.
=> Add a first guess of automatic testing

.github/workflows/codecov.yml, README.md
I have added codecoverage via the codecov Gh Actions CI and a badge in the README
=> Add ci for codecoverage and badge

.github/workflows/codecov.yml
adjusted the tests folder to correctly cover the tested code
=> Adjust tests folder

.dockerignore, Dockerfile, README.md
Adjust Dockerfile, add .dockerignore and improve README.md.
=> Fixes and adjustments

wetterdienst/cli.py
Some more adjustments to account for the renaming.
=> cli.py: Naming things

CHANGELOG.md, README.md, poetry.lock, pyproject.toml, tests/additionals/test_geo_location.py, wetterdienst/__init__.py, wetterdienst/additionals/geo_location.py
I updated get_nearest_station:
- renamed it to get_nearby_stations
- has an additional distance argument to choose from
Besides that the return values/types were not consistent for selection one stations in opposition to selecting more stations. I tried to fix that but it needs a future refactoring for sure.
Check it out!
=> Update get_nearest_station, fix tests

CHANGELOG.md, wetterdienst/additionals/util.py, wetterdienst/cli.py
Dear Benjamin,
this builds upon #102 (thanks already!) and brings the feature for _filtering by distance_ to the command line.
Andreas.
P.S.: Nearly all features of [dwdweather2](https://github.com/panodata/dwdweather2/) are now available within **Wetterdienst**. Thanks again for your willingness to absorb its functionality into this code base.
=> Bring geospatial filtering by distance to the command line

CHANGELOG.md, README.md, pyproject.toml
Version bumped to 0.2.0 and changelog completed
=> Bump version, add to changelog

CHANGELOG.md, wetterdienst/additionals/functions.py, wetterdienst/data_collection.py
Type casting for integer fields fixed for cases with nans in the series. Also fixed humanizing fields for the tidy data.
=> Fix integer type casting and humanizing of column names for tidy data

tests/additionals/test_functions.py, tests/additionals/test_geo_location.py, wetterdienst/additionals/functions.py, wetterdienst/additionals/geo_location.py, wetterdienst/constants/parameter_mapping.py, wetterdienst/constants/time_resolution_mapping.py, wetterdienst/enumerations/time_resolution_enumeration.py
Fix bug occured with TimeResolution.MINUTE_10 and DWDOrigDataColumns  in humanize column names
=> Bugifx DWDOrigDataColumns names does not match enumeration

.dockerignore, Dockerfile
- README.md has been renamed to README.rst.
- While being at it, also upgrade some versions.
=> Fix Docker

.gitignore, CHANGELOG.rst, README.rst, docs/index.rst, docs/pages/api.rst, docs/pages/changelog.rst, docs/pages/cli.rst, docs/pages/data_coverage.rst, docs/pages/development.rst, docs/pages/installation.rst
Nomen est omen. I hope you like it.
=> Update documentation all over the place

.flake8, CHANGELOG.rst, noxfile.py, poetry.lock, pyproject.toml, tests/test_cli.py, wetterdienst/additionals/geo_location.py, wetterdienst/additionals/util.py, wetterdienst/cli.py
Hi there,
the CLI has been broken, this should fix it again. It also adds corresponding software tests to prevent future havocs.
Cheers,
Andreas.
=> Make the CLI work again

README.rst, docs/index.rst, docs/pages/api.rst, docs/pages/behind_the_scenes.rst, docs/pages/cli.rst, docs/pages/data_coverage.rst, docs/pages/development.rst, docs/pages/installation.rst, docs/pages/library/api.rst, docs/pages/library/core.rst, docs/pages/library/index.rst, docs/pages/library/machinery.rst, docs/pages/license_and_citation.rst, wetterdienst/additionals/functions.py, wetterdienst/additionals/geo_location.py, wetterdienst/api.py, wetterdienst/data_collection.py, wetterdienst/data_models/coordinates.py, wetterdienst/data_storing.py, wetterdienst/download/download.py, wetterdienst/download/download_services.py, wetterdienst/enumerations/column_names_enumeration.py, wetterdienst/parse_metadata.py
Dear Benjamin,
these updates adjust the documentation once more. I hope you like them.
Cheers,
Andreas.
=> Another round of updates to the documentation

README.rst, docs/index.rst, docs/pages/behind_the_scenes.rst, docs/pages/library/index.rst, docs/pages/welcome.rst
Trying to work around https://github.com/earthobservations/wetterdienst/issues/155#issuecomment-692975055 ff. here.
- Copy/paste README.rst into welcome.rst in order to fix Sphinx PDF build. Sorry for that.
- Also, adjust some other bits and pieces within the documentation.
=> Copy/paste README.rst into welcome.rst in order to fix Sphinx PDF build

.readthedocs.yml, docs/conf.py, docs/pages/tutorial.rst, docs/requirements.txt, poetry.lock, pyproject.toml
In order to integrate #167 properly, we need to install `wetterdienst` and its dependencies within the RTD environment. Otherwise, the Sphinx IPython renderer will not be able to do its job at all.
=> Fix docs dependencies

docs/pages/development.rst, docs/pages/installation.rst
Hi there,
this updates the documentation about Docker images available from ghcr.io according to https://github.com/earthobservations/wetterdienst/issues/171#issuecomment-696324703.
Andreas.
=> Update documentation about Docker images available from ghcr.io

poetry.lock, pyproject.toml, wetterdienst/additionals/cache.py, wetterdienst/download/download.py, wetterdienst/indexing/file_index_creation.py
Adjust cache ttl values appropriately.
=> Adjust cache ttl values

poetry.lock, pyproject.toml, tests/additionals/test_geo_location.py
Just some version updates. Let's see how CI will respond.
=> Bump some dependency packages

tests/test_cli.py, wetterdienst/cli.py
This will increase coverage of `cli.py` by +15.04%. Total coverage for the whole code base will go back to >90%.
=> Improve tests to cover more of cli.py

.flake8, CHANGELOG.rst, docs/index.rst, docs/pages/api.rst, docs/pages/installation.rst, docs/pages/service.rst, noxfile.py, poetry.lock, pyproject.toml, tests/test_service.py, wetterdienst/__init__.py, wetterdienst/cli.py, wetterdienst/pandas/io.py, wetterdienst/service.py
Hi again,
these are some first steps for implementing a HTTP API to the core machinery.
Just invoke:
```
wetterdienst service
```
And then submit some HTTP requests:
```
http localhost:7890/api/dwd/stations station==1048,4411 parameter==kl resolution==daily period==recent
http localhost:7890/api/dwd/observations station==1048,4411 parameter==kl resolution==daily period==recent
```
See also more examples at [pages/service.rst](https://github.com/earthobservations/wetterdienst/blob/2e5cb2bdbc66df26a51c1cacf578696bcc9c3a2a/docs/pages/service.rst).
Andreas.
P.S.: The program for submitting the HTTP requests is [HTTPie](https://httpie.org/).
=> Add basic HTTP API

tests/additionals/test_functions.py, wetterdienst/additionals/functions.py
As just discussed with @gutzbenj...
=> Adjust type coercion

.github/release/full/Dockerfile, .github/release/standard/Dockerfile, CHANGELOG.rst, Dockerfile
=> Upgrade Docker images to Python 3.8.6

README.rst, docs/pages/api.rst, docs/pages/welcome.rst, example/observations_hdf5.py, example/observations_sites.py, wetterdienst/dwd/observations/api.py, wetterdienst/dwd/observations/store.py
A small followup to #204.
- Update documentation and snippets about new HDF5 storage adapter.
- Also, add a dedicated example demonstrating the new functionality.
=> Followup to new HDF5 storage adapter

wetterdienst/dwd/observations/store.py
=> Fix CLI output

CHANGELOG.rst, poetry.lock, pyproject.toml, tests/dwd/radar/test_api_historic.py
@steffen746 reported problems with timezones on Windows, see #222. Apart from that, this also addresses #223, otherwise the tests on CI would have failed.
=> Fix problems with timezones on Windows

wetterdienst/util/pandas.py
Some updates to the inline documentation.
=> Fix inline comments in data export routines

.github/workflows/coverage.yml, .github/workflows/docker-publish-full.yml, .github/workflows/docker-publish-standard.yml, .github/workflows/docs.yml, .github/workflows/linter.yml, .github/workflows/release.yml, .github/workflows/tests.yml, poetry.lock, pyproject.toml, tests/dwd/observations/test_api_data.py, tests/test_cli.py, tests/test_service.py, wetterdienst/cli.py, wetterdienst/dwd/forecasts/api.py, wetterdienst/dwd/observations/parser.py, wetterdienst/dwd/pandas.py, wetterdienst/dwd/util.py, wetterdienst/service.py, wetterdienst/util/pandas.py
I integrated the dwd forecasts option into the CLI and Service, making use of the DWDMosmixSites and DWDMosmixData APIs. It follows the same structure as for dwd observations but still lacks some features like to_geojson which will have to be added on a later iteration.
=> Integrated forecast/mosmix information in cli and service

tests/dwd/radar/test_api_latest.py
It looks like this picked up data from a five minute slot of the previous hour.
=> Fix flaky radar test once more

CHANGELOG.rst, poetry.lock, pyproject.toml, tests/dwd/radar/test_api_historic.py
Maybe this solves #272 already?
cc @wetterfrosch
=> Bump "h5py" to version 3.1.0 to satisfy installation on Python 3.9

.github/workflows/coverage.yml, .github/workflows/docker-publish-full.yml, .github/workflows/docker-publish-standard.yml, .github/workflows/docs.yml, .github/workflows/linter.yml, .github/workflows/release.yml, .github/workflows/tests.yml, noxfile.py, pyproject.toml
Python 3.9.0 will be released soonish.
Branch | Schedule | Status | First release | End-of-life | Release manager
-- | -- | -- | -- | -- | --
3.9 | PEP 596 | bugfix | 2020-10-05 | TBD | Łukasz Langa
-- https://devguide.python.org/#status-of-python-branches
=> Add support for Python 3.9

.github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/docker-publish-full.yml, .github/workflows/docker-publish-standard.yml, .github/workflows/docs.yml, .github/workflows/linter.yml, .github/workflows/release.yml, .github/workflows/tests.yml
This makes use of the Github Caching action as well as Poetry action for Poetry setup in accordance with #266 .
=> Use Poetry action and Cache action for CI

README.rst, docs/conf.py, docs/pages/welcome.rst, poetry.lock, pyproject.toml, tests/dwd/radar/test_api_current.py, tests/dwd/radar/test_api_historic.py, tests/dwd/radar/test_api_invalid.py, tests/dwd/radar/test_api_latest.py, tests/dwd/radar/test_api_most_recent.py, tests/dwd/radar/test_api_recent.py, tests/test_readme.py
=> Fix docs building, add test for README.rst

docs/data/coverage/dwd.rst, tests/dwd/radar/test_api_historic.py
A link to the available DWD radar products is added.
Fixes #248
=> Add an overview of DWD radar products

.github/workflows/tests.yml
Hi there,
while we are satisfied with the GHA workflow in general, specifically after introducing the `actions/cache` action which gave the job a tremendous boost, we still have been observing problems that the cache apparently does not get honored on Windows environments.
While @gutzbenj already tried hard on #328, there is still hassle with it. So, this is another attempt from my pen where I want to humbly reach out to @sondrelg on behalf of https://github.com/snok/install-poetry/issues/18.
Thanks already for your help on this, Sondre!
Andreas.
=> Fix Poetry environment caching on CI/GHA/Windows

CHANGELOG.rst, pyproject.toml, wetterdienst/__init__.py
Add imports of Provider and Kind to top-level
=> Bump version to 0.15.0

.github/dependabot.yml, CHANGELOG.rst, README.rst, THIRD_PARTY_NOTICES, docs/usage/api.rst, example/mosmix_forecasts.py, example/observations_sql.py, example/observations_stations.py, poetry.lock, requirements.txt, tests/provider/dwd/forecast/test_api_data.py, tests/provider/dwd/observation/test_api_data.py, tests/provider/dwd/observation/test_io.py, tests/provider/dwd/test_util.py, wetterdienst/cli.py, wetterdienst/core/scalar/request.py, wetterdienst/core/scalar/result.py, wetterdienst/core/scalar/values.py, wetterdienst/provider/dwd/forecast/api.py, wetterdienst/provider/dwd/observation/api.py, wetterdienst/provider/eccc/observation/api.py, wetterdienst/service.py
Rename some more parameters for better readability.
- `humanize_parameters` -> `humanize`
- `tidy_data` -> `tidy`
=> Rename humanize_parameters to humanize and tidy_data to tidy

CONTRIBUTORS.rst, pyproject.toml
- Update pyproject.toml keywords and contributors
=> Update pyproject.toml and contributors

.github/release/full.test.yml, .github/release/full/Dockerfile, .github/release/selftest.sh, .github/release/standard.test.yml, .github/release/standard/Dockerfile, .github/workflows/release.yml
Along the lines, bump to Python 3.8.8 within Docker containers.
=> Fix build and improve Docker image testing

CHANGELOG.rst, poetry.lock, pyproject.toml, tests/provider/dwd/observation/test_api_metadata.py, tests/test_cli.py, wetterdienst/api.py, wetterdienst/core/scalar/request.py, wetterdienst/provider/dwd/forecast/api.py, wetterdienst/provider/dwd/forecast/metadata/field_types.py, wetterdienst/provider/dwd/observation/api.py, wetterdienst/provider/dwd/observation/metadata/field_types.py, wetterdienst/provider/eccc/observation/metadata/parameter.py
- also: 
- change field types from tuple to set
- bump version to 0.16.1
- add **poe install_dev** to install library with all optionals
=> Fix discover method to return all strings in lower

wetterdienst/provider/eccc/observation/api.py
Hi there,
this patch fixes the apparent flakyness with the FTP server at `ftp.tor.ec.gc.ca`. It is the better alternative than e60666b.
Andreas.
=> ECCC: Provide another source for acquiring "Station Inventory EN.csv"

CHANGELOG.rst, poetry.lock, pyproject.toml, tests/provider/dwd/observation/test_io.py, tests/provider/dwd/radar/test_api_latest.py, wetterdienst/cli.py, wetterdienst/provider/eccc/observation/api.py, wetterdienst/util/pandas.py
Hi there,
while support for exporting data to Parquet files was only added recently, this also adds an early version of "export to Zarr format".
Andreas.
=> Add export to Zarr format

wetterdienst/provider/dwd/radar/access.py
This is an attempt to mitigate a hiccup I just observed on CI on behalf of #409.
=> Try to improve robustness when receiving EOFErrors on reading RADOLAN

README.rst, docs/usage/python-api.rst, poetry.lock, tests/provider/dwd/observation/test_api_data.py, tests/provider/dwd/observation/test_api_metadata.py, tests/provider/dwd/observation/test_io.py, tests/provider/dwd/radar/test_api_most_recent.py, tests/test_api.py, tests/test_docs.py, wetterdienst/core/scalar/request.py, wetterdienst/core/scalar/values.py, wetterdienst/provider/dwd/forecast/api.py, wetterdienst/provider/dwd/forecast/metadata/unit.py, wetterdienst/provider/dwd/observation/api.py, wetterdienst/provider/dwd/observation/fileindex.py, wetterdienst/provider/dwd/observation/metadata/unit.py, wetterdienst/provider/eccc/observation/api.py, wetterdienst/provider/eccc/observation/metadata/unit.py, wetterdienst/ui/cli.py, wetterdienst/ui/restapi.py
Fix bug in unit conversion and add tests for unit conversion
=> Fix bug in unit conversion and add tests for unit conversion

docs/data/coverage/dwd.rst, wetterdienst/provider/eccc/observation/metadata/dataset.py, wetterdienst/provider/eccc/observation/metadata/parameter.py, wetterdienst/provider/eccc/observation/metadata/unit.py
- fix spelling mistake in ECCC parameters (wind_spreed -> wind_speed)
- add data coverage for DWD Mosmix in docs
=> Fix spelling mistake in ECCC parameters and add more coverage in docs

README.rst, tests/test_docs.py
=> Make "test_readme" work again

CHANGELOG.rst, tests/provider/eccc/test_api.py, wetterdienst/provider/eccc/observation/api.py
- also: fix method of data acquisition from ECCC
=> Add baseline test for ECCC observations

README.rst, tests/provider/dwd/radar/__init__.py, wetterdienst/__init__.py, wetterdienst/provider/dwd/__init__.py, wetterdienst/provider/eccc/__init__.py, wetterdienst/provider/eumetnet/__init__.py
-also: Fix some radar test regex
=> Fix import error in README

CHANGELOG.rst, THIRD_PARTY_NOTICES, poetry.lock, requirements.txt, wetterdienst/__init__.py
This fixes the show method using __appname__ for version identification.
Fixes #466
=> Fix show method

wetterdienst/provider/dwd/observation/api.py
A wrong attribute was used to adress a DWD observation dataset
=> Fix bug with tidy method of DWD observation data

CHANGELOG.rst, example/radar/radar_radolan_cdc.py, poetry.lock, pyproject.toml, tests/provider/dwd/radar/test_index.py, tests/ui/test_restapi.py, wetterdienst/provider/dwd/radar/access.py, wetterdienst/provider/dwd/radar/api.py, wetterdienst/provider/dwd/radar/index.py, wetterdienst/provider/dwd/radar/metadata/parameter.py
- Fix DWD radar acquisition using the main Wetterdienst Period and Resolution
- Adjust DWD radar composite parameters to new index
Fixes 
#479 
#478
=> Fix DWD radar acquisition 

CHANGELOG.rst, poetry.lock, pyproject.toml, tests/ui/test_restapi.py, wetterdienst/provider/dwd/forecast/access.py, wetterdienst/provider/dwd/forecast/api.py, wetterdienst/provider/dwd/observation/download.py, wetterdienst/provider/eccc/observation/api.py
-Fix restapi test with recent period
-Get rid of performance warning for dwd mosmix data
=> Fix restapi test with recent period and performance warning of DWD Mosmix data

README.rst
=> README: Fix link to documentation

CHANGELOG.rst, THIRD_PARTY_NOTICES, docs/usage/python-api.rst, poetry.lock, pyproject.toml, requirements.txt, wetterdienst/util/cache.py, wetterdienst/util/network.py
- add variable FSSPEC_CLIENT_KWARGS at wetterdienst.util.cache that is passed to fsspec filesystem to allow the user to specify things like ssl, proxy,...
=> Allow specification of request kwargs for fsspec

CHANGELOG.rst, wetterdienst/core/scalar/values.py
=> Add missing positional dataset argument for empty parameter df

CHANGELOG.rst, THIRD_PARTY_NOTICES, poetry.lock, requirements.txt, tests/provider/dwd/observation/test_api_data.py, tests/provider/eccc/__init__.py, wetterdienst/core/scalar/values.py, wetterdienst/provider/dwd/observation/api.py
=> Fix timestamps for 1 minute / 10 minute DWD data before 2000

poetry.lock, pyproject.toml, tests/provider/dwd/observation/test_io.py, tests/provider/dwd/radar/test_api_historic.py, tests/ui/test_cli.py, wetterdienst/__init__.py, wetterdienst/core/scalar/export.py, wetterdienst/core/scalar/request.py, wetterdienst/provider/dwd/forecast/api.py, wetterdienst/provider/dwd/observation/fields.py, wetterdienst/provider/dwd/radar/cli.py, wetterdienst/provider/dwd/radar/sites.py, wetterdienst/ui/cli.py, wetterdienst/ui/explorer/app.py, wetterdienst/ui/explorer/library.py
Added checks for print statements, builtins and list comprehensions
=> Add more lint checks

.github/workflows/tests.yml, CHANGELOG.rst, THIRD_PARTY_NOTICES, poetry.lock, requirements.txt, tests/provider/dwd/radar/test_api_historic.py, tests/test_api.py, wetterdienst/core/scalar/values.py, wetterdienst/provider/noaa/ghcn/api.py, wetterdienst/provider/noaa/ghcn/parameter.py
A problem is fixed that led to NOAA GHCN dates being NaT after dates coersion. This was due to the dates already being parsed with timezones, which led the afterwards tz localization to fail.
The test for the general api was slightly adjusted to test for existence of values and dates only, omitting quality which could be NaN for some weather services.
=> Adjust dates coercing with timezones slightly

poetry.lock, tests/test_api.py, wetterdienst/core/scalar/values.py
Slightly adjust general api test
=> Fix ECCC to also contain station id within the returned values DataFrame

CHANGELOG.rst, THIRD_PARTY_NOTICES, poetry.lock, requirements.txt, tests/ui/explorer/test_explorer.py, tests/ui/test_restapi.py, wetterdienst/ui/cli.py, wetterdienst/ui/restapi.py
Previously discovered by @amotl cli returned not actually json but dict-style printouts. Also as discovered now by @Elfe the restapi did return NaN instead of NULL. This PR fixes both issues.
Fixes #592
=> Fix restapi to return NULL instead of NaN and ensure json for cli

CHANGELOG.rst, THIRD_PARTY_NOTICES, poetry.lock, pyproject.toml, requirements.txt, tests/provider/dwd/observation/test_api_data.py, wetterdienst/provider/dwd/observation/metadata/dataset.py
Shorthand fix for belows issue. Reminder: We should add more cross checks between parameters and units to make sure no confusions are happening between dataset and parameter names.
This PR also fixes an issue related with the latest added test for monthly dwd observation data that was constrained by recent which would produce different results after some time...
Fixes #608
=> Rename sun dataset according to previous changes

CHANGELOG.rst, pyproject.toml
=> Bump version to 0.31.1

CHANGELOG.rst, poetry.lock, wetterdienst/core/scalar/values.py
=> Fix creation of empty dataframe for annual data

CHANGELOG.rst, THIRD_PARTY_NOTICES, poetry.lock, requirements.txt, wetterdienst/provider/environment_agency/hydrology/api.py, wetterdienst/ui/explorer/app.py
Dear all,
there was an error for specific stations where the `measures` item in the returned values json is not an array but a dictionary. This PR fixes the issue by wrapping those specific cases into an array.
Also the resolution type was set to fixed although it should be multi, which was fixed.
Cheers
Benjamin
=> Fix EA hydrology access

.github/workflows/docker-publish-full.yml, .github/workflows/docker-publish-standard.yml
Update Docker publish workflows to use Python 3.10 and snok poetry setup action
=> Update Docker publish workflows

README.rst
Apparently, this patch was still sitting in some branch I've pushed the other day, but I never pressed the button to create a corresponding pull request.
=> Documentation: Update badges in README

.github/workflows/tests.yml, pyproject.toml
Python 3.11 will be released in about a month, on 2022-10-24.
=> Add support for Python 3.11

CHANGELOG.rst, tests/provider/dwd/mosmix/test_api_data.py, wetterdienst/provider/dwd/mosmix/api.py
Start and end date where previously not considered for filtering data returned by DwdMosmixRequest. This PR fixes this issue.
Fixes #757
=> Fix DwdMosmixRequest date filter

.github/workflows/tests.yml, CHANGELOG.rst, README.rst, benchmarks/summary_over_time.py, docs/usage/python-api.rst, poetry.lock, tests/core/scalar/test_summary.py, wetterdienst/core/scalar/request.py, wetterdienst/core/scalar/result.py, wetterdienst/core/scalar/summarize.py, wetterdienst/core/scalar/tools.py
Dear all,
this PR adds a summary method as requested at #703 . It is pretty similar to interpolation and basically I could reuse lots of code so props go out to @neumann-nico . I didn't have too many thoughts about it so probably there will be some changes in the feature, but it already works quite nice as shown by the benchmark!
Currently I have set similar restrictions as with interpolation so we may lift those at some point all together.
I'm happy that this implementation could be done so quickly so enjoy it and have a nice day!
Cheers
Benjamin
Fixes #703
=> Add summarize method

CHANGELOG.rst, tests/provider/dwd/observation/test_api_data.py, wetterdienst/core/scalar/values.py, wetterdienst/provider/dwd/observation/metadata/parameter.py, wetterdienst/provider/dwd/observation/metadata/unit.py, wetterdienst/provider/dwd/observation/parser.py
Dear all,
we've seen at #695 that the access to urban data had still caused some trouble as reported by @RJVogel. This is another attempt, removing a non described column.
Also all available datasets are now tested against station `Berlin-Alexanderplatz` to make sure everything works.
Cheers,
Benjamin
Fixes #695
=> Fix DWD Observation urban_pressure dataset access (again)

CHANGELOG.rst, tests/provider/noaa/ghcn/test_api_data.py, tests/ui/test_cli.py, wetterdienst/core/scalar/values.py, wetterdienst/metadata/resolution.py, wetterdienst/provider/noaa/ghcn/api.py
Dear all,
@nhcb reported again some problems with NOAA GHCN data. After lookin at it I realized there's an error with timezones once again.
This PR tries to improve the situation around building a complete dataframe. I could remove some other helper function I had built the other day and largely simplify the function. 
I also used the chance to add some simple cut off method for start and end date to avoid errors when requesting dates with too fine granularity.
E.g. when start date is 1970-01-01 01:01 and only daily data is requested -> strip away hour and second with which we can perfectly fine build a complete date range that can be joined on!
I hope this solves our issues with timezones for some time at least ;)
=> Fix timezone mapping when building complete df

CHANGELOG.rst, tests/ui/test_cli.py, tests/ui/test_restapi.py, wetterdienst/ui/cli.py, wetterdienst/ui/core.py, wetterdienst/ui/restapi.py
Dear all,
I added interpolate/summarize to restapi/cli.
It is fascinating (at least to me) how easy things seem to be pluggable here! 
Just added two small tests per restpi/cli that equal mostly the library based tests where we test interpolation of values and usage of existing station values (station was opened at a certain date after which interpolation is not done anymore).
Fixes #749
=> UI: Add interpolate and summarize methods as subspaces

CHANGELOG.rst, poetry.lock, pyproject.toml, tests/provider/dwd/radar/__init__.py, tests/provider/dwd/radar/conftest.py, tests/provider/dwd/radar/test_api_historic.py, tests/provider/dwd/radar/test_api_latest.py, tests/provider/dwd/radar/test_api_most_recent.py
Dear all,
this PR leverages https://dirty-equals.helpmanual.io/ to improve our dictionary tests and allow more broad testing data.
=> Improve radar tests

CHANGELOG.rst, LICENSE, README.rst, docs/conf.py, docs/usage/cli.rst, docs/usage/explorer.rst, pyproject.toml, tests/core/scalar/test_interpolation.py, tests/provider/dwd/observation/test_api_data.py, tests/provider/dwd/observation/test_available_datasets.py, tests/test_api.py, tests/ui/explorer/test_explorer.py, wetterdienst/__init__.py, wetterdienst/boot.py, wetterdienst/ui/cli.py, wetterdienst/util/cli.py, wetterdienst/util/enumeration.py, wetterdienst/util/fsspec_monkeypatch.py, wetterdienst/util/pdf.py, wetterdienst/util/python.py
Hi again,
this patch is a potpourri of different things.
- Mitigate deprecation notices
- Reorganize pytest settings in `pyproject.toml`
- CLI improvements of various kinds
Cheers,
Andreas.
=> Maintenance: This and that

example/observations_station_gaussian_model.py
Hello Andreas and Benjamin,
Ive added the `.py` module in this PR for the example, as we discussed in https://github.com/MyPyDavid/HeFDI-Forschungsdatentag-2022/issues/6.
What do you think about it? Ive made the codestyle `black` already.
Cheers,
David
=> add an example with a gaussian model fitting

CHANGELOG.rst, docs/data/coverage/dwd/mosmix/hourly.rst, docs/data/coverage/dwd/observation/annual.rst, docs/data/coverage/dwd/observation/daily.rst, docs/data/coverage/dwd/observation/hourly.rst, docs/data/coverage/dwd/observation/minute_1.rst, docs/data/coverage/dwd/observation/minute_10.rst, docs/data/coverage/dwd/observation/minute_5.rst, docs/data/coverage/dwd/observation/monthly.rst, docs/data/coverage/eccc/observation/annual.rst, docs/data/coverage/eccc/observation/daily.rst, docs/data/coverage/eccc/observation/monthly.rst, docs/data/coverage/noaa/ghcn/daily.rst, docs/data/coverage/wsv/pegel/dynamic.rst
=> Docs: Fix precipitation units

CHANGELOG.rst, wetterdienst/provider/dwd/observation/fileindex.py
There was an error in the followup of cleanings steps when creating the fileindex.
=> Fix dwd observations 1 minute fileindex

tests/ui/explorer/test_explorer.py, wetterdienst/ui/explorer/app.py
Another fix for explorer. We can actually select stations via the station_id instead of latlon.
=> Fix explorer app

README.rst
The links point to the resources in my rdwd package that are updated a few times per year.
=> added links to dwd data overviews

poetry.lock, wetterdienst/core/timeseries/values.py, wetterdienst/provider/geosphere/observation/api.py
=> Fix Geosphere parameter case

CHANGELOG.rst, tests/provider/geosphere/observation/test_api.py, wetterdienst/provider/geosphere/observation/api.py
thanks to @mhuber89 who discovered the bug and delivered a fix
Fixes #982
=> Fix Geosphere Observation parsing of dates in values

poetry.lock, pyproject.toml, tests/provider/dwd/observation/test_api_data.py, tests/provider/imgw/hydrology/test_api.py, tests/provider/imgw/meteorology/test_api.py, tests/test_api.py, tests/test_settings.py, wetterdienst/core/core.py, wetterdienst/core/timeseries/request.py, wetterdienst/core/timeseries/values.py, wetterdienst/monkeypatch/fsspec_monkeypatch.py, wetterdienst/provider/dwd/dmo/api.py, wetterdienst/provider/dwd/mosmix/api.py, wetterdienst/provider/dwd/radar/sites.py, wetterdienst/provider/imgw/meteorology/api.py, wetterdienst/provider/noaa/ghcn/api.py, wetterdienst/provider/noaa/ghcn/parameter.py, wetterdienst/provider/noaa/ghcn/unit.py, wetterdienst/ui/streamlit/app.py
In between, along the lines of bumping the version of the Ruff linter, a round of code formatting, and improving the sandbox.
=> Dependencies: Use ruff==0.0.291. Format code.

poetry.lock, pyproject.toml
=> Dependencies: Bump a few more, using timestamp-based versioning

CHANGELOG.rst, wetterdienst/ui/streamlit/app.py
=> Improve streamlit app plotting capabilities

example/radar/radar_composite_rw.py, example/radar/radar_radolan_cdc.py, example/radar/radar_radolan_rw.py, example/radar/radar_scan_precip.py, example/radar/radar_scan_volume.py, example/radar/radar_site_dx.py, example/radar/radar_sweep_hdf5.py, poetry.lock, pyproject.toml
@amotl @gutzbenj 
I've used the online editor for the first time, so this is all untested. Let's see if this works out of the box.
=> Update to wradlib 2.0

CHANGELOG.rst, tests/provider/dwd/observation/test_api_data.py, wetterdienst/core/timeseries/values.py, wetterdienst/provider/dwd/observation/api.py, wetterdienst/provider/dwd/observation/metaindex.py, wetterdienst/provider/dwd/observation/parser.py
Dear @lasinludwig ,
this is for you and the DWD issues. Thanks again for reporting the issues! I also added a test case for the `wind_extreme` dataset. 
Fixes #1013
=> Fix multiple issues with DwdObservationRequest API

docs/usage/cli.rst, wetterdienst/ui/cli.py
This patchset will be similar to GH-851, and will accumulate some fixes, probably mostly in the CLI region.
- CLI: Improve help text by making examples work
=> Maintenance: This and that, round 2

CHANGELOG.rst, poetry.lock, pyproject.toml, tests/core/timeseries/test_io.py, tests/util/test_url.py, wetterdienst/core/timeseries/export.py, wetterdienst/util/polars_util.py, wetterdienst/util/url.py
This adds support for influxdb v3 export.
Not sure about the cli calls like `influx setup...`
=> Export: Add support for InfluxDB 3.x

CHANGELOG.rst, docs/data/coverage/dwd/observation.rst, docs/data/coverage/dwd/observation/minute_5.rst, tests/provider/dwd/observation/test_api_data.py, wetterdienst/provider/dwd/observation/parser.py
=> Fix DWD Observation API for 5 minute data

CHANGELOG.rst, tests/core/timeseries/test_interpolation.py, tests/core/timeseries/test_io.py, tests/core/timeseries/test_summary.py, tests/ui/cli/test_cli.py, tests/ui/test_restapi.py, wetterdienst/core/timeseries/interpolate.py, wetterdienst/core/timeseries/request.py, wetterdienst/core/timeseries/result.py, wetterdienst/core/timeseries/summarize.py, wetterdienst/metadata/columns.py
Also:
- Rename taken station ids columns for interpolation and summarization
=> Use artificial station id for interpolation and summarization

wetterdienst/provider/dwd/radar/api.py
This should fix the datetimes for dwd radar products, which are almost all now available in five minute steps. See https://github.com/earthobservations/wetterdienst/discussions/1143.
=> DWD Radar: fix datetime adjustment

CHANGELOG.rst, wetterdienst/core/timeseries/values.py, wetterdienst/provider/dwd/observation/metaindex.py
=> Adjust column specs for DWD Observation station listing

docs/usage/restapi.rst
=> Fix restapi docs

pyproject.toml, requirements-dev.lock, requirements.lock
@guidocioni maybe this helps?
@kmuehlbauer numpy>2 should not be blocked anymore with this
=> Remove upper bounds

CHANGELOG.rst, examples/provider/dwd/mosmix/dwd_mosmix_forecasts.py, examples/provider/dwd/mosmix/dwd_mosmix_validation.py, tests/provider/dwd/mosmix/test_api_data.py, wetterdienst/core/timeseries/result.py, wetterdienst/core/timeseries/values.py, wetterdienst/provider/dwd/dmo/api.py, wetterdienst/provider/dwd/mosmix/access.py, wetterdienst/provider/dwd/mosmix/api.py, wetterdienst/ui/core.py
Also: Allow only single issue retrieving with `DWDMosmixRequest` and `DWDDmoRequest`
Fixes #1357
=> Change `DWDMosmixValues` and `DWDDmoValues` to follow the core `_collect_station_parameter` method

CHANGELOG.rst, docs/data/coverage/dwd/road.rst, docs/data/coverage/dwd/road/minute_15.rst, tests/provider/dwd/road/test_api.py, wetterdienst/provider/dwd/road/api.py
=> DWD Road: Use correct 15 minute resolution

docs/data/coverage/dwd/observation.rst
Commit bf9a4ee6c78d1a91a2c58dbf28f2ff6327430992 renamed the `examples/dwd_describe_fields.py` example to be `examples/provider/dwd/observation/dwd_obs_climate_summary_describe_fields.py`. This PR adjusts sources to changes.
=> Update example reference

CHANGELOG.md, Dockerfile
Dear @neumann-nico @amotl ,
do you think anything stands against cleaning up the Docker image? I think there were quite some workarounds in the past, that are not needed anymore!
Sincerely,
Benjamin
=> Cleanup docker image
