earthobservations/wetterdienst

- python_dwd/additionals/helpers.py
I fixed possible errors with datetime conversion using pd.to_datetime. I compared both files for more_precip and kl, both daily resolution and histroical period. There were obviously no differences between both metadata files but still, the conversion would throw an error for the kl file. That's why I replaced pd.to_datetime with the datetime64 class from numpy and this way there's no more problems.
> Fix datetime conversion by replace pd.to_datetime with datetime64 class

- python_dwd/additionals/helpers.py
- python_dwd/constants/metadata.py
- python_dwd/constants/variables.py
- python_dwd/metadata_dwd.py
- python_dwd/parsing_data/parse_data_from_files.py
I did changes on the 1 minute metadata:
- I tested the function after the recent changes (where saving the zip on the disk was replaced by storing it in bytes) and it seemed to me, that the old errors, where one engine of pandas would fail for some file, wasn't popping up anymore. This way I removed the double try-except by simply using the default engine ("c") always. I also used this issue to remove the set strings for nas ("-999") and the seperator (";") by variables that are set in the metadata constants.
> Work on 1 minute metadata

- python_dwd/additionals/helpers.py
- python_dwd/constants/metadata.py
The metadata for 1minute precipitation historical differs indeed from the recent data so that I could not replace the functionality. Also I tried to speed it up which was not really successfull (which means it still takes around 3 minutes to create metadata for 1minute precipitation hist). However I used the chance to clean the code and structure it a bit more.
> Refactor metadata 1minute precipitation

- python_dwd/data_collection.py
Dear Daniel and Benjamin,
we found a minor glitch (probably coming from a typo) which was hard to spot but we believe is an important fix.
As the body of the `collect_dwd_data()` method already iterates over the set of `station_ids`, we should pass the **single** `station_id` down to `create_file_list_for_dwd_server()` instead of all the `station_ids` again.
Otherwise, when redundantly adding data for **all** obtained `station_ids` within each iteration, the data frame will contain duplicate information which happened to show bad behavior for us when working on the CLI feature as outlined within #50.
Specifically, Pandas would croak with `ValueError("cannot reindex from a duplicate axis")` when applying boolean filters on indices of concatenated data frames containing duplicate data. We …
> Fix minor glitch within "collect_dwd_data"

- python_dwd/additionals/helpers.py
Hi there,
The description of the `lstrip` method is _»Return a copy of the string with leading characters removed.«_ While that sounds nice, it is not quite what we want here.
The syntax is actually `str.lstrip([chars])` where "chars" is a string specifying the **set of characters** to be removed. The chars argument is not a prefix; rather, all combinations 
of its values are stripped.
Actually, this goes south when trying to "strip away" the `DWD_PATH` prefix because "annual" will become "ual" and "monthly" will become "hly".
```
>>> DWD_PATH = 'climate_environment/CDC/observations_germany/climate'
>>> filename = 'climate_environment/CDC/observations_germany/climate/annual/kl/historical/jahreswerte_KL_13777_20090101_20181231_hist.zip'
>>> filename.lstrip(DWD_PATH + '/') …
```
> Fix filename cleansing within "create_fileindex"

- python_dwd/enumerations/period_type_enumeration.py
Quoting @gutzbenj:
> Ordering is required for the PeriodType enumeration in order for it to be sorted. PeriodType needs to be sortable for the request definition where for the case of requesting data for several periods, we want preferably the historical data with quality marks and drop overlapping values from other periods.
-- Backported to `master` from `stationdata-request-definition`, authored by @gutzbenj.
> Make PeriodType enumeration sortable

- .gitignore
- pytest.ini
- python_dwd/additionals/helpers.py
- python_dwd/additionals/util.py
- python_dwd/cli.py
- python_dwd/constants/column_name_mapping.py
- python_dwd/constants/metadata.py
- python_dwd/data_collection.py
- python_dwd/download/download.py
- python_dwd/dwd_station_request.py
- python_dwd/enumerations/column_names_enumeration.py
- python_dwd/file_path_handling/file_list_creation.py
- python_dwd/metadata_dwd.py
- python_dwd/parsing_data/parse_data_from_files.py
- requirements.txt
- setup.py
- tests/additionals/test_geo_location.py
- tests/file_path_handling/test_file_list_creation.py
- tests/test_data_collection.py
Dear Benjamin and Daniel,
as outlined within #50, we wanted to start bringing the features of this library to the command line similar to what users have been accustomed with [dwdweather2](https://github.com/panodata/dwdweather2).
Thanks again for the ongoing efforts you are putting into this library. Being able to acquire data across historical+recent data sets using the new `DWDStationRequest.collect_data()` method without having to assemble them manually in any way is really powerful.
While we haven't tested any other combinations of parameters other than those listed within the examples section of `dwd --help` yet, you might want to merge these updates right away when pulling in the `stationdata-request-definition` branch to master. Saying that, there might well be some fixups …
> Add command line interface

- python_dwd/cli.py
- python_dwd/dwd_station_request.py
Hi there,
this adjusts the parameter name `humanize_column_names`. I named it a bit different before and that typo has slipped through somehow.
Andreas.
> Fix parameter typo within the "cli" feature

- python_dwd/additionals/helpers.py
- python_dwd/data_collection.py
- python_dwd/parsing_data/parse_data_from_files.py
- tests/parsing_data/test_parse_data_from_files.py
- tests/test_data_collection.py
Data from the `hourly` time resolution has a timestamp format of e.g. `2018121300`. So, let's parse it using the custom timestamp pattern `%Y%m%d%H`.
> Properly handle timestamps from "hourly" resolution data set

- python_dwd/additionals/helpers.py
Hi again,
This is another thing we learned from maintaining [`dwdweather2`](https://github.com/panodata/dwdweather2) I would like to share in form of code with you.
The DWD directory structure has an anomaly: For **solar** data, there are no "recent" or "historical" folders within the "hourly" and "daily" time resolutions, see [1,2]. Sad but true.
When applying this minor fix accounting for the deviation outlined above, this command starts working flawlessly:
```
dwd readings --station=183,662 --parameter=solar --resolution=daily --period=recent --date=2020-05-31
```
As soon as #63 gets merged, it should probably also start working for hourly data.
Andreas.
[1] https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/solar/
[2] …
> Fix data acquisition for solar data from hourly and daily resolutions

- python_dwd/constants/access_credentials.py
- python_dwd/download/download.py
- python_dwd/download/download_services.py
- python_dwd/enumerations/column_names_enumeration.py
- python_dwd/exceptions/failed_download_exception.py
I had to change the FTP_EXPRESSION to HTTPS_EXPRESSION and the `to_list()` is not working with the pd.Series.
type hinting is not necessary at this point. If you parse pd.Series to numpy.array and a numpy.array to a List, the output is a List defined by the called pipeline.
> Bug fix series to list

- CHANGELOG.md
- wetterdienst/cli.py
Hi there,
both `wetterdienst stations|readings` now accept `--latitude` and `--longitude` parameters. Optionally, `--count` can be added to adjust the number of nearby stations. Default: 1.
```
wetterdienst stations --resolution=daily --parameter=kl --period=recent --lat=50.2 --lon=10.3 --count=10
wetterdienst readings --resolution=daily --parameter=kl --period=recent --lat=50.2 --lon=10.3 --count=10 --date=2020-06-30
```
Cheers,
Andreas.
> Bring geospatial filtering to the command line

- CHANGELOG.md
- tests/test_parse_metadata.py
- wetterdienst/additionals/geo_location.py
- wetterdienst/cli.py
Hi again,
this is another feature from [dwdweather2](https://github.com/panodata/dwdweather2/). With these updates, the user will be able to output station information in [GeoJSON format](https://tools.ietf.org/html/rfc7946), which is useful for a bunch of Web-GIS stuff [like within Leaflet](https://leafletjs.com/examples/geojson/).
Cheers,
Andreas.
> Add GeoJSON output format for station data

- tests/additionals/test_functions.py
- tests/test_data_storing.py
- wetterdienst/additionals/functions.py
- wetterdienst/download/download_services.py
- wetterdienst/enumerations/column_names_enumeration.py
- wetterdienst/indexing/meta_index_creation.py
- wetterdienst/parsing_data/parse_data_from_files.py
The additional column name enumerations are used to extend the conversion of dtypes to correctly handle integers and strings
> Dtype conversion is extended to integer fields and string fields

- CHANGELOG.md
- tests/test_dwd_station_request.py
- wetterdienst/data_collection.py
- wetterdienst/dwd_station_request.py
I extended the DWDStationRequest class and simplified the init process a bit. Now we are able to request multiple parameters at once. The **collect_data** method will now return one DataFrame per station including multiple parameters (this may change in the future, should we see any performance problems with this). 
With this change, we will be able to fullfill #106. @amotl please have a look at the changes I've set to make this work!
> Extend request class to be able to request multiple parameters at once

- .github/workflows/coverage.yml
- .github/workflows/linter.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- poetry.lock
- pyproject.toml
This makes some version bumps. The tests pass on my machine on Python 3.8.3 and CI will tell us about any other things.
> Update sandbox/infrastructure dependencies across the board

- README.rst
- docs/pages/development.rst
- pytest.ini
- tests/additionals/test_geo_location.py
- tests/example/test_notebooks.py
- tests/test_api.py
- tests/test_data_collection.py
- tests/test_parse_metadata.py
Hi there,
this is just a small fixup.
It adds the `FIXED_METADATA.json` mock to another test function and decorates some other test functions with `@pytest.mark.remote` and `@pytest.mark.slow`. The marks significantly help in order to speed up the test cycle.
When invoked using `time pytest -vvvv -m "not (remote or slow)"`:
```
real	0m3.800s
user	0m2.786s
sys	0m0.488s
```
When invoked using `time pytest -vvvv`:
```
real	2m15.609s
user	0m59.317s
sys	0m18.932s
```
Andreas.
> Slightly improve tests

- .flake8
- wetterdienst/cli.py
This brings #149 to the command line.
```
$ wetterdienst about coverage --resolution=daily --parameter=kl
{
"TimeResolution.DAILY": {
"Parameter.CLIMATE_SUMMARY": [
"PeriodType.HISTORICAL",
"PeriodType.RECENT"
]
}
}
```
```
$ wetterdienst about coverage --resolution=daily
{
"TimeResolution.DAILY": {
"Parameter.CLIMATE_SUMMARY": [
"PeriodType.HISTORICAL",
"PeriodType.RECENT"
],
"Parameter.PRECIPITATION_MORE": [
"PeriodType.HISTORICAL",
"PeriodType.RECENT"
],
"Parameter.TEMPERATURE_SOIL": [
"PeriodType.HISTORICAL",
"PeriodType.RECENT"
],
"Parameter.SOLAR": [
"PeriodType.RECENT"
],
"Parameter.WATER_EQUIVALENT": [
"PeriodType.HISTORICAL",
"PeriodType.RECENT"
],
"Parameter.WEATHER_PHENOMENA": [
"PeriodType.HISTORICAL",
"PeriodType.RECENT"
]
}
}
```
> Add "wetterdienst about coverage" to command line interface

- CHANGELOG.rst
- docs/conf.py
- docs/requirements.txt
- poetry.lock
- pyproject.toml
This switches to [Material for Sphinx](https://bashtage.github.io/sphinx-material/), which provides a more modern documentation look & feel. Also, it renders tremendously better on mobile devices.
> Use "Material for Sphinx" theme for documentation

- docs/conf.py
- docs/requirements.txt
- wetterdienst/additionals/functions.py
- wetterdienst/additionals/geo_location.py
- wetterdienst/api.py
- wetterdienst/data_collection.py
- wetterdienst/data_storing.py
- wetterdienst/download/download.py
- wetterdienst/download/download_services.py
- wetterdienst/parse_metadata.py
Hi there,
this adds [sphinx-autodoc-typehints](https://github.com/agronholm/sphinx-autodoc-typehints) as suggested by @larsrinn (thanks!) within #136. Now, there's no need for manually annotating these with `:type` and `:rtype` docstrings any more.
Andreas.
> [docs] Add sphinx-autodoc-typehints

- README.rst
- docs/conf.py
- docs/pages/development.rst
Hi there,
this tries to improve the situation with #155. `make latexpdf` now works again.
Cheers,
Andreas.
> Fix PDF generation with Sphinx

- wetterdienst/constants/parameter_mapping.py
Dear Benjamin and @e-dism,
after catching up on #147, I believe we might want to improve the situation transparently without going the extra mile to make the user even aware of this anomaly.
The implementation under the hood already compensates for this anomaly and so we should give this feature thoroughly back to the user without sacrificing it by pushing the obstacle to another place.
Please let me know if you have any objections on this. The tests will still pass and things like that will conveniently work without further ado:
```
wetterdienst readings --station=1048,4411 --parameter=air_temperature,solar --resolution=hourly --period=historical --persist --date=2017-09-16T12
```
Cheers,
Andreas.
P.S.: For all others reading this: The background of this issue is that the DWD data folder …
> Compensate compensation for DWD folder anomaly at "hourly/solar" on the parameter level

- wetterdienst/data_storing.py
Dear Benjamin,
thanks for adding RADOLAN support through #129 the other day. This brings in a minor fix when used with the `write_file=True` option.
Andreas.
> Fix RADOLAN data acquisition when used with "write_file=True"

- CHANGELOG.rst
- docs/pages/api.rst
- example/radolan.py
Dear Benjamin,
this adds an `example/radolan.py` and adjusts the documentation within the RADOLAN section of `api.rst`.
Andreas.
> Add "example/radolan.py" and adjust documentation

- docs/conf.py
- docs/index.rst
- docs/pages/tutorial.rst
- docs/requirements.txt
- wetterdienst/additionals/functions.py
Dear Benjamin,
regarding #136, I gave `IPython.sphinxext.ipython_directive` a shot. With the updates coming from this PR, the iPython Sphinx extension will work in general, but currently will fail when actually hitting code from Wetterdienst [1].
Currently, I am clueless about how to solve this and will be happy if you could take a look. To reproduce, just invoke
```
cd docs
make html
```
on this branch.
Cheers,
Andreas.
[1] I've used code from [`example/simple_example.ipynb`](https://github.com/earthobservations/wetterdienst/blob/v0.7.0/example/simple_example.ipynb) for that. Thanks!
cc @larsrinn
> Add tutorial stub based on iPython Sphinx extension

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- wetterdienst/additionals/cache.py
- wetterdienst/data_collection.py
- wetterdienst/download/download.py
- wetterdienst/download/download_services.py
- wetterdienst/indexing/file_index_creation.py
- wetterdienst/indexing/meta_index_creation.py
Dear Benjamin,
this replaces the `@lru_cache` caching by a persistent one based on `dogpile.cache` - currently a file-based dbm caching store. This will tremendously speed up successive invocations of Wetterdienst when using the same set of parameters.
Right now, it will not work on Windows though. We would have to make the test backend more configurable within another iteration.
Andreas.
> Add TTL-based persistent caching using dogpile.cache

- tests/indexing/test_file_index_creation.py
- tests/indexing/test_meta_index_creation.py
- tests/test_parse_metadata.py
These calls might not be required. If we strictly need an empty cache before running the tests, we should provide a pytest fixture calling out to `reset_meta_index_cache()` and `reset_file_index_cache()`.
> Remove reset_{meta,file}_index_cache() from tests

- .coveragerc
- .flake8
- .gitignore
- CHANGELOG.rst
- README.rst
- docs/pages/api.rst
- docs/pages/cli.rst
- docs/pages/development.rst
- docs/pages/installation.rst
- example/sql.py
- noxfile.py
- poetry.lock
- pyproject.toml
- tests/test_cli.py
- tests/test_io.py
- tests/test_run.py
- wetterdienst/__init__.py
- wetterdienst/cli.py
- wetterdienst/io.py
Hi there,
This introduces `wetterdienst.io` in order to establish a backplane for different postprocessing tasks. This is what I roughly had in mind when writing about "Ingest data from DWD and conveniently submit it to different data sinks" within https://github.com/earthobservations/wetterdienst/issues/142#issuecomment-690821061. It builds upon things coming from `wetterdienst.cli` and tries to generalize its functionality into a new `DataPackage` class.
For demonstrating these features, let's define an alias first:
```
alias fetch='wetterdienst readings --station=1048,4411 --parameter=kl --resolution=daily --period=recent'
```
Currently, exporting to SQLite, DuckDB, InfluxDB, CrateDB and other SQL databases is implemented.
```
fetch --target="sqlite:///dwd.sqlite&table=weather"
fetch …
```
> Emit data to different data sinks and query interactively using SQL

- CHANGELOG.rst
- docs/pages/api.rst
- example/mosmix.py
- poetry.lock
- pyproject.toml
- tests/file_path_handling/test_path_handling.py
- tests/test_mosmix.py
- wetterdienst/constants/access_credentials.py
- wetterdienst/file_path_handling/path_handling.py
- wetterdienst/indexing/file_index_creation.py
- wetterdienst/indexing/meta_index_creation.py
- wetterdienst/mosmix.py
Hi there,
This is a first shot at #70 and has been derived from the [`dwdbulk::forecasts`](https://github.com/jlewis91/dwdbulk/blob/master/dwdbulk/api/forecasts.py) implementation by @jlewis91. Thanks a bunch!
```
poetry update
poetry shell
python wetterdienst/mosmix.py
```
- Column names and such have not been integrated into the Enum-based knowledgebase yet.
- As outlined within https://github.com/earthobservations/wetterdienst/issues/70#issuecomment-653690214, it would be cool to reuse additional code from @FL550's [`dwdforecast.py`](https://github.com/FL550/simple_dwd_weatherforecast/blob/master/simple_dwd_weatherforecast/dwdforecast.py) implementation.
> I like that it already maps the technical meteorological element names to more meaningful field names (see #54). Also, it features …
> Add DWD MOSMIX client and parser

- .dockerignore
- .github/release/full.test.yml
- .github/release/full/Dockerfile
- .github/release/standard.test.yml
- .github/release/standard/Dockerfile
- .github/workflows/docker-publish-full.yml
- .github/workflows/docker-publish-standard.yml
- poetry.lock
- pyproject.toml
Hi there,
in order to adress https://github.com/earthobservations/wetterdienst/issues/171#issuecomment-696331182 ff., this will invoke `poetry build --format=wheel` and will install that wheel package inside the Docker container instead of acquiring the package from PyPI.
It also adjusts the selection of dependencies for `wetterdienst-standard` and `wetterdienst-full` images.
Cheers,
Andreas.
> Fix official Docker image building by using wheel from working tree

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- tests/dwd/test_pandas.py
- tests/test_service.py
Hi there,
@Mytherin from DuckDB fame was so kind to add support for the Pandas Int64 type and timezone-aware Pandas Timestamp objects quickly, see https://github.com/cwida/duckdb/issues/959 and https://github.com/cwida/duckdb/pull/960.
So, after switching to DuckDB 0.2.2.dev254, everything started working again. Excellent - thanks @Mytherin!
Cheers,
Andreas.
> Activate SQL querying again by using DuckDB 0.2.2.dev254

- CHANGELOG.rst
- wetterdienst/dwd/observations/api.py
This fixes data filtering by date for cases where no data in general is available for a given station and selected parameter.
> Fix date filtering for cases of no data being available

- CHANGELOG.rst
- tests/test_cli.py
- wetterdienst/cli.py
- wetterdienst/dwd/pandas.py
This improvement makes it optional to output results in "tidy"-format.
> CLI: Obtain "--tidy" argument from command line

- tests/dwd/radar/test_api_historic.py
- tests/dwd/radar/test_api_latest.py
Hi there,
radar tests are more often painful than not. Some radar sites are not always reporting data, so we have to compensate.
When this keeps going on, we might want to mark them with `@pytest.mark.radar` and exclude them from being invoked on GHA by using `pytest -m "not radar"`.
The rationale behind this is: While it is okay for me to keep on improving them iteratively by compensating for missing radar sites, it will be weird when contributions from others might be coming in and CI will croak at them.
Andreas.
cc @kmuehlbauer
> Fix flaky radar tests again

- docs/pages/api.rst
- tests/dwd/observations/test_api_data.py
- wetterdienst/dwd/observations/api.py
The dwd observations API was adjusted to accomodate the suggest changes at #225. Now even if start and end date are defined the given  periods are used. Automated selection of periods according to start and end date was rejected due to the unclear update process of the different files of the DWD - no clear statement exists upon the timing of the publishing of new versions of recent/now packages of data.
> Adjust periods to be used also for cases with defined start and end date

- CHANGELOG.rst
- tests/dwd/test_pandas.py
- wetterdienst/dwd/observations/api.py
- wetterdienst/util/pandas.py
Hi there,
this improves some aspects on the InfluxDB export reported by @wetterfrosch. Thanks!
- Fix export in non-tidy format (resolve #230).
- Use "quality" column as tag (see #234).
Andreas.
> Improvements for InfluxDB export

- CHANGELOG.rst
- wetterdienst/util/pandas.py
Within #235, @wetterfrosch observed errors like
```
influxdb.exceptions.InfluxDBClientError: 413: {"error":"Request Entity Too Large"}
```
when writing larger amounts of data into InfluxDB.
By using `batch_size=50000`, things start working again.
> InfluxDB export: Use a batch size of 50000 to handle larger amounts of data

- CHANGELOG.rst
- example/radar/radar_scan_precip.py
- example/radar/radar_scan_volume.py
- example/radar/radar_site_dx.py
- example/radar/radar_sweep_hdf5.py
- poetry.lock
- pyproject.toml
- tests/dwd/observations/test_api_data.py
- tests/dwd/test_pandas.py
- wetterdienst/dwd/observations/parser.py
Some `wradlib` reader functions are now able to consume file-like objects. So, the use of `tempfile` can be removed at some places. Thanks, @kmuehlbauer!
Closes #251.
> Update radar examples to use "wradlib>=1.9.0"

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- tests/dwd/observations/test_api_data.py
- tests/dwd/observations/test_fileindex.py
- tests/dwd/observations/test_parser.py
- wetterdienst/dwd/metadata/column_names.py
- wetterdienst/dwd/metadata/constants.py
- wetterdienst/dwd/observations/access.py
- wetterdienst/dwd/observations/api.py
- wetterdienst/dwd/observations/fileindex.py
- wetterdienst/dwd/observations/metadata/resolution.py
- wetterdienst/dwd/observations/parser.py
- wetterdienst/dwd/observations/store.py
- wetterdienst/dwd/pandas.py
- wetterdienst/dwd/util.py
This should improve on efficiency in situations like outlined by @wetterfrosch at #256.
The summary of what I am trying here:
- At the `1_minute`/`10_minute` resolutions, before starting the actual collection, let's look for the corresponding date strings in the file name.
- These are used for the local memory then.
- If no record is found there, use `collect_observations` again.
- Now, there is an additional parameter `datestring` which is used for filtering. This has been extracted before to access the local memory.
> Efficient historical data acquistion with dynamic periods

- CHANGELOG.rst
- docs/index.rst
- docs/pages/dwd_quality.rst
- example/dwd_describe_fields.py
- tests/dwd/observations/test_api_metadata.py
- wetterdienst/cli.py
- wetterdienst/dwd/observations/api.py
- wetterdienst/dwd/observations/fields.py
Dear @larsrinn,
in order to support #228 a bit, this improves the DWD PDF parser to also extract quality information and select the output language. As this is rather a hack, this feature has not been documented yet. However, it is the best thing Wetterdienst has to offer so far.
In order to get started with it quickly, I added an example program at `example/dwd_describe_fields.py`.
In the long run, we should bring this information into a respective knowledgebase module within the code base itself. Even for doing that, these helper routines might prove useful.
Andreas.
---
As an example, these are the PDF files on `opendata.dwd.de` I am referring to:
- [DESCRIPTION_obsgermany_climate_daily_kl_recent_en.pdf](https://opendata.dwd.de/climate_environment/CDC/observations_ger …
> Improve DWD PDF parser to extract quality information and select language

- poetry.lock
- pyproject.toml
Thanks to https://github.com/nat-n/poethepoet we can again use comfortable shortcuts (that we had with nox) for black codeformatting, linting and testing with the following:
- poe black
- poe lint
- poe test
> Add poethepoet for comfortable black, lint and test

- wetterdienst/cli.py
This removes the DWIM date filter for the cli stations function, which had resulted in some problems in #236 . The filter may be added later on once again with a more finetuned behaviour.
> Remove DWIM date filter for cli stations

- CHANGELOG.rst
- poetry.lock
- wetterdienst/dwd/observations/api.py
- wetterdienst/dwd/observations/fileindex.py
This fixes an error that is caused by the fileindex intervals not having a timezone thus filtering by the given start and end dates had failed before. Now uses UTC to make filtering possible.
> Add timezone information to fileindex intervals

- setup.py
Hi there,
through [1], we learned that this might bring back the "Used by" widget on the right hand side of the GitHub front page. Thanks a stack, @willmcgugan.
Andreas.
[1] https://github.com/willmcgugan/rich/blob/master/setup.py
> Add "setup.py" shim to make GitHub detect this as a Python package

- CHANGELOG.rst
- example/observations_stations.py
- poetry.lock
- tests/dwd/observations/test_api_data.py
- tests/dwd/radar/test_api_most_recent.py
- tests/dwd/test_date.py
- tests/dwd/test_pandas.py
- wetterdienst/core/scalar.py
- wetterdienst/dwd/forecasts/api.py
- wetterdienst/dwd/observations/api.py
- wetterdienst/dwd/pandas.py
- wetterdienst/dwd/util.py
- wetterdienst/exceptions.py
- wetterdienst/util/datetime.py
Date parsing is changed to isoformat only using the module
dateutil.parser.isoparse
Fixes #258 , #247
> Make dates timezone aware, restrict date parsing to isoformat

- README.rst
- docs/data/coverage/dwd.rst
- docs/usage/api.rst
Hi there,
some spots have been missed after renaming the "master" branch to the "main" branch. This patch accounts for that.
Andreas.
> Fix renaming of "master" branch to "main" branch on some spots

- CHANGELOG.rst
- tests/dwd/radar/test_sites.py
- wetterdienst/dwd/radar/sites.py
Hi there,
according to https://github.com/wradlib/wradlib-notebooks/issues/49#issuecomment-768262146, Emden is missing in the official publication [koordinaten-radarverbund.pdf](https://www.dwd.de/DE/derdwd/messnetz/atmosphaerenbeobachtung/_functions/HaeufigGesucht/koordinaten-radarverbund.pdf?__blob=publicationFile). Thanks for spotting this, @kmuehlbauer.
a) This patch adds it back. Can you verify the coordinates, Kai?
b) We should also notify `opendata@dwd.de` about it.
Andreas.
> DWD: Add missing radar site "Emden" (EMD, wmo=10204)

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- tests/dwd/observations/test_api_stations_geo.py
- wetterdienst/dwd/observations/api.py
> Fix date filtering of DWD observations

- CHANGELOG.rst
- README.rst
- docs/usage/api.rst
- poetry.lock
- requirements.txt
- tests/dwd/forecasts/test_api_data.py
- tests/dwd/forecasts/test_api_stations.py
- tests/test_api.py
- tests/test_cli.py
- tests/util/test_geo.py
- wetterdienst/__init__.py
- wetterdienst/api.py
- wetterdienst/core/core.py
- wetterdienst/core/scalar/request.py
- wetterdienst/core/scalar/result.py
- wetterdienst/core/scalar/values.py
- wetterdienst/dwd/forecasts/api.py
- wetterdienst/dwd/observations/api.py
- wetterdienst/exceptions.py
- wetterdienst/metadata/kind.py
- wetterdienst/metadata/provider.py
- wetterdienst/util/geo.py
This adds a top-level API to the library. From here we can get our wished API like
```python
from wetterdienst import Wetterdienst
API = Wetterdienst("dwd", "observation")
request = API("kl", "daily", "recent").filter(station_id=(1048, ))
stations = request.df
values = request.values.all().df
```
The constructor raises a ValueError if the combination of weather service and kind of data is not available.
> Add top-level API

- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/linter.yml
- .github/workflows/tests.yml
- .gitignore
- CHANGELOG.rst
- README.rst
- poetry.lock
- pyproject.toml
- tests/core/test_scalar_values.py
- tests/dwd/observations/test_api_data.py
- tests/dwd/radar/test_api_historic.py
- tests/dwd/radar/test_api_latest.py
- tests/dwd/radar/test_api_most_recent.py
- tests/dwd/radar/test_api_recent.py
- tests/dwd/radar/test_index.py
- tests/dwd/test_io.py
- tests/dwd/test_pandas.py
- tests/test_cli.py
- tests/test_service.py
- tests/util/test_url.py
- wetterdienst/cli.py
- wetterdienst/core/scalar/values.py
- wetterdienst/dwd/observations/metadata/column_types.py
- wetterdienst/dwd/pandas.py
- wetterdienst/service.py
- wetterdienst/util/pandas.py
- wetterdienst/util/url.py
Hi there,
this patch supersedes #277 and finally brings in the capability to export to Feather and Parquet file formats. At the same time, it repairs export features for other targets like InfluxDB and CrateDB. For doing that, it now needs Pandas 1.2 which will in turn implicitly deprecate support for Python 3.6.
After integrating this patch, commands like this will start working:
```sh
wetterdienst dwd observations values \
--station=1048,4411 --parameter=kl --resolution=daily --period=recent --target="file://test.parquet"
```
Andreas.
P.S.: Also, in order to get past CI, the radar test suite had to be improved in order to make it more graceful again.
> Add capability to export to Feather- and Parquet-files and more I/O subsystem polishing

- poetry.lock
- pyproject.toml
- tests/provider/dwd/observation/test_api_data.py
- wetterdienst/core/core.py
- wetterdienst/core/scalar/request.py
- wetterdienst/provider/dwd/observation/api.py
Hi there,
this patch doesn't convert timestamps back and forth from/to strings and back if not needed at all.
Along the lines, it adjusts one test to use a different time delta. Otherwise, this test would fail due to current daylight saving time switchover happening in Germany. However, we should investigate this further.
Andreas.
> Improve timestamp parsing

- tests/provider/dwd/radar/test_api_current.py
- tests/provider/dwd/radar/test_api_historic.py
- tests/provider/dwd/radar/test_api_latest.py
- tests/provider/dwd/radar/test_api_most_recent.py
- tests/provider/dwd/radar/test_api_recent.py
With this patch, I tried to improve the test situation with radar a bit. Some tests have been marked as `xfail`, where I tried to use more conditional runtime `skip`s instead, like:
```python
if len(results) == 0:
raise pytest.skip("Data currently not available")
```
> Tests: Fix some xfailing radar tests

- CHANGELOG.rst
- README.rst
- poetry.lock
- pyproject.toml
- tests/__init__.py
- tests/provider/dwd/observation/test_io.py
- tests/provider/dwd/radar/test_api_current.py
- tests/provider/dwd/radar/test_api_historic.py
- tests/provider/dwd/radar/test_api_most_recent.py
- tests/provider/dwd/radar/test_api_recent.py
- wetterdienst/util/cache.py
With this patch we want to improve the situation about working with mac arm64. We have some dependencies with additional markers, so that they wont be installed on those system as of now. Further hints are given in the readme on how to install core libraries like pandas - which atm needs to be done BEFORE installing the library itself.
Further changes had to be done to satisfy dogpile.cache.
> Improve project dependencies to resolve errors with MAC ARM64

- .gitignore
- CHANGELOG.rst
- example/radar/radar_composite_rw.py
- example/radar/radar_radolan_cdc.py
- example/radar/radar_radolan_rw.py
- example/radar/radar_scan_precip.py
- example/radar/radar_scan_volume.py
- example/radar/radar_site_dx.py
- example/radar/radar_sweep_hdf5.py
- poetry.lock
- pyproject.toml
- tests/example/test_regular_examples.py
- tests/provider/dwd/radar/test_api_historic.py
- tests/provider/dwd/radar/test_util.py
- wetterdienst/provider/dwd/radar/access.py
- wetterdienst/provider/dwd/radar/api.py
- wetterdienst/provider/dwd/radar/util.py
Hi,
while trying to bring [1] up to speed (see https://github.com/wradlib/wradlib-notebooks/pull/51), I observed occasional data acquisition errors. Apparently, two files of the whole acquired sweep data set have not been valid HDF5, so `wrl.io.open_odim(files)` croaked on it and hasn't been able to skip the invalid ones.
With this patch, HDF5 responses will be verified by Wetterdienst for being valid HDF5 files before returning them in the result. All invalid items are logged with level WARNING, including their URL.
Along the lines, this patch also improves some other radar tests again.
Andreas.
[1] https://github.com/wradlib/wradlib-notebooks/blob/v1.9.0/notebooks/fileio/wradlib_load_DWD_opendata_volumes.ipynb
cc @kmuehlbauer
> Radar: Verify HDF5 responses instead of returning invalid data

- tests/ui/test_restapi.py
- wetterdienst/ui/restapi.py
Hi Benjamin,
this patch just adjusts another occurrance where I would prefer long names over short names.
Andreas.
> REST API: Rename query parameters "lat" and "lon" to their long variants

- THIRD_PARTY_NOTICES
- poetry.lock
- pyproject.toml
- requirements.txt
- wetterdienst/core/scalar/request.py
This replaces FuzzyWuzzy with RapidFuzz (disclaimer: I am the author) for the following reasons:
- The current usage with FuzzyWuzzy is broken:
https://github.com/earthobservations/wetterdienst/blob/76aae17d7bf15d5369407904196e82d56ab96460/wetterdienst/core/scalar/request.py#L509-L526
process.extract in FuzzyWuzzy does not has an argument `score_cutoff` (I think there has been a PR to add it for a long time, but FuzzyWuzzy is not really actively maintained), so it would throw an exception when someone passes `first=False`. RapidFuzz has pretty much the same interface, but provides a `score_cutoff` argument for process.extract.
- It is a lot faster than FuzzyWuzzy even when it is used with python-Levenshtein
- It is MIT licensed. Since Wetterdienst is MIT Licensed as well, I think it is …
> Replace FuzzyWuzzy with RapidFuzz

- CHANGELOG.rst
- THIRD_PARTY_NOTICES
- poetry.lock
- wetterdienst/provider/dwd/forecast/api.py
Mosmix stations file is now cache similarly to DWD metaindex. Also the method was simplified by applying some filter to the rows with no values. 
fixes #412
> Apply caching to Mosmix stations

- tests/provider/dwd/radar/test_api_historic.py
- tests/provider/dwd/radar/test_api_latest.py
- tests/provider/dwd/radar/test_api_most_recent.py
- tests/ui/explorer/test_ui.py
Some version embedded into the radar files has been bumped from 2.28.1 to 2.29.1. This patch accounts for that.
> Fix radar tests

- docs/usage/explorer.rst
- tests/provider/dwd/radar/test_api_historic.py
There was a typo with the port number within the documentation.
> Fix "Wetterdienst Explorer" documentation about Docker port

- README.rst
- tests/provider/dwd/radar/__init__.py
Hi,
we renamed some of the Python package "extras" labels. This patch accounts for that and fixes the sandbox setup documentation.
Andreas.
> Fix sandbox setup documentation

- CHANGELOG.rst
- docs/usage/python-api.rst
- wetterdienst/util/cache.py
Hi there,
the patch from #418 by @meteoDaniel introduces optional `WD_CACHE_DIR` and `WD_CACHE_DISABLE` environment variables. Thanks a stack.
This is a PR based on this patch in order fix some minor issues and prepare the integration.
Andreas.
> Improve caching behaviour

- README.rst
- wetterdienst/__init__.py
From #433 we received hints on how to get wetterdienst running on Raspberry Pi. Prior to the installation the user has to run two apt-get commands in order to get numpy and lxml working.
> Add further notes on issues

- CHANGELOG.rst
- tests/provider/dwd/radar/__init__.py
- wetterdienst/provider/dwd/forecast/api.py
Bizarrely we were using next() to return Mosmix data, which led to the generator only returning data for the first station. Thanks to @tsjfd we could fix this.
fixes #446
> Fix DWD Mosmix generator to return all contained dataframes

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- tests/provider/dwd/observation/test_io.py
- wetterdienst/core/scalar/export.py
- wetterdienst/util/pandas.py
Hi there,
this patch brings in some improvements from the discussion at #456.
- Add support for authentication and SSL with InfluxDB 1.x
- Add support for InfluxDB 2.x
- Use InfluxDBClient instead of DataFrameClient for improved handling of `null` values
Thanks a stack to everyone who contributed.
Andreas.
/cc @JSAnyone
> Improve InfluxDB support

- CHANGELOG.rst
- README.rst
- THIRD_PARTY_NOTICES
- poetry.lock
- requirements.txt
- wetterdienst/core/scalar/export.py
- wetterdienst/core/scalar/request.py
- wetterdienst/provider/dwd/forecast/api.py
- wetterdienst/provider/dwd/observation/api.py
Our InfluxDB export was recently croaking. When experementing with the tidy formatted data export, I found that the error results from empty fields. To fix this now dates with empty fields are just skipped.
Fixes #456
> Fix InfluxDB export by skipping empty fields

- CHANGELOG.rst
- tests/ui/test_cli.py
- wetterdienst/__init__.py
- wetterdienst/ui/cli.py
This adds a method show() that prints basic information about the used wetterdienst instance. Currently we have
- version
- authors
- documentation
- repository
- cache dir
We should further add environment settings like tidy, si_units,... as defaults as soon as those settings are separated from the classes.
Fixes #246
> Add show method for wetterdienst instance

- wetterdienst/core/scalar/values.py
- wetterdienst/provider/dwd/forecast/api.py
- wetterdienst/provider/dwd/observation/api.py
This PR resolves some further problems with tidying taking parts from subfunctions (implemented at provider specific apis) to main level and this reducing redundancy. Also parameter types are actually already coerced correctly after tyding however this closes this issue fully.
Fixes #377
> Improve tidying function

- CHANGELOG.rst
- README.rst
@amotl has provided a snippet on how to setup a sandbox installation for developers, which can hold as alternative to the snipped we were providing before and which seemed to cause trouble in some environments.
Fixes #421
> Update readme part of sandbox developer installation

- CHANGELOG.rst
- THIRD_PARTY_NOTICES
- docs/usage/python-api.rst
- docs/usage/python-examples.rst
- poetry.lock
- requirements.txt
- tests/provider/dwd/observation/test_api_data.py
- tests/provider/dwd/radar/test_api_historic.py
- tests/ui/test_cli.py
- tests/ui/test_core.py
- wetterdienst/core/scalar/request.py
- wetterdienst/core/scalar/values.py
- wetterdienst/provider/dwd/forecast/access.py
- wetterdienst/provider/dwd/observation/api.py
- wetterdienst/provider/dwd/observation/fileindex.py
- wetterdienst/provider/dwd/radar/access.py
- wetterdienst/provider/eccc/observation/api.py
- wetterdienst/ui/cli.py
- wetterdienst/ui/core.py
Hey there,
this enables the definition of parameters by giving a tuple of (parameter, dataset).
Currently we have presets of parameters per resolution e.g. daily precipitation height is currently taken from the the climate summary dataset although there's a similar parameter in the precipitation_more dataset.
**Why is this of interest?**
We can not clearly tell all the differences of the parameters found in the different datasets but for some the measurement instruments and principles (e.g. rounding the hourly value vs taking an instant value at the end of an hour)
can differ. This information can be found in each zip file!
Now we can query a parameter providing a tuple of parameter and dataset like
```python
request = DwdObservationRequest(
...,
parameter=[("precipitation_height", …
```
> Enable defining parameter and dataset together

- CHANGELOG.rst
- poetry.lock
- wetterdienst/provider/dwd/observation/api.py
For DWD Observation data with high resolutions we want to query multiple files, but only as many as needed if start_date and end_date is provided. Therefor we build the interval and check overlapping files (each file usually has a given interval e.g. one month. 
However when no start_date and end_date is provided, which is the case if the user wants to query all available data chunks, the request interval results in None. This small patch fixes that issue, setting the interval to the maximum range of dates for the given files, if no start_date and end_date is provided.
Fixes #497
> Fix bug with DWD Observation request that results in interval being None

- CHANGELOG.rst
- README.rst
- docs/usage/cli.rst
- tests/ui/test_cli.py
- wetterdienst/__init__.py
- wetterdienst/ui/cli.py
We had some code snippets in the README that invoked `wetterdienst --version` and `wetterdienst info`. This updates them to `wetterdienst version` and `wetterdienst info`
> Fix deprecated code snippets

- wetterdienst/core/scalar/request.py
- wetterdienst/core/scalar/values.py
- wetterdienst/metadata/unit.py
- wetterdienst/provider/dwd/forecast/api.py
- wetterdienst/provider/dwd/forecast/metadata/unit.py
- wetterdienst/provider/dwd/observation/api.py
- wetterdienst/provider/dwd/observation/metadata/unit.py
- wetterdienst/provider/eccc/observation/api.py
- wetterdienst/provider/eccc/observation/metadata/unit.py
Origin and SI Unit enums are merged to prevent misspelling of parameters and other related issues. Instead origin and SI unit are stored in the same place as tuple. This also reduces the number of external objects that have to be created to implement a new weather service and basically, units are stored in the same place.
> Merge unit enums

- THIRD_PARTY_NOTICES
- poetry.lock
- requirements.txt
- tests/provider/dwd/observation/test_download.py
- wetterdienst/exceptions.py
- wetterdienst/provider/dwd/observation/download.py
This patch improves #431. Now that we are trying to use fsspec for every possible file interaction, we may as well use the ZipFilesystem for interaction with the zipfiles we are acquiring from the DWD.
> Use fsspec.ZipFilesystem for accessing resources from DWD

- CHANGELOG.rst
- wetterdienst/provider/dwd/radar/index.py
Radar tests have recently failed because some files were duplicated on the server side and stored as additional .bz2 file. This is fixed by simply filtering out those files when creating the index.
> Fix radar index by filtering out bz2 files

- CHANGELOG.rst
- THIRD_PARTY_NOTICES
- poetry.lock
- requirements.txt
- wetterdienst/provider/eccc/observation/api.py
ECCC ftp server can not be reached anymore. Luckily they have put the stations listing on a separate Google Drive folder from which it can be accessed via request. This PR uses fsspec to get the stations listing (cached) from that folder, alternatively falling back to our backup at Github.
> Fix ECCC stations listing access

- CHANGELOG.rst
- tests/provider/dwd/observation/test_api_data.py
- tests/test_docs.py
- wetterdienst/provider/dwd/observation/api.py
- wetterdienst/provider/dwd/observation/fileindex.py
There was a bug where the DWD intervals where not using tz information but rather overwriting it. With the help of freezegun we can also test recent + now period.
> Fix DWD intervals and add test for recent plus now interval

- CHANGELOG.rst
- README.rst
- THIRD_PARTY_NOTICES
- docs/library/core.rst
- docs/usage/python-api.rst
- example/mosmix_forecasts.py
- example/observations_sql.py
- example/observations_stations.py
- poetry.lock
- pyproject.toml
- requirements.txt
- tests/provider/dwd/forecast/test_api_data.py
- tests/provider/dwd/observation/test_api_data.py
- tests/provider/dwd/observation/test_io.py
- tests/provider/dwd/test_util.py
- tests/provider/eccc/test_api.py
- tests/test_api.py
- tests/test_settings.py
- tests/ui/test_cli.py
- wetterdienst/__init__.py
- wetterdienst/core/scalar/request.py
- wetterdienst/provider/dwd/forecast/api.py
- wetterdienst/provider/dwd/observation/api.py
- wetterdienst/provider/eccc/observation/api.py
- wetterdienst/provider/noaa/ghcn/api.py
- wetterdienst/settings.py
- wetterdienst/ui/core.py
- wetterdienst/ui/explorer/app.py
This PR introduces new wetterdienst settings, that manage all kinds of general settings about scalar requests, caching dirs, etc.
Backlog:
Related issue: #572
> Add wetterdienst settings with general settings

- CHANGELOG.rst
- tests/provider/eccc/test_api.py
- tests/provider/noaa/ghcn/test_api_stations.py
- wetterdienst/provider/dwd/mosmix/api.py
- wetterdienst/provider/eccc/observation/api.py
- wetterdienst/provider/noaa/ghcn/api.py
Further data is added to the NOAA GHCN stations listing from http://noaa-ghcn-pds.s3.amazonaws.com/ghcnd-inventory.txt that contains start and end date of all elements of all stations.
> Add details about time interval for NOAA GHCN stations

- CHANGELOG.rst
- THIRD_PARTY_NOTICES
- poetry.lock
- pyproject.toml
- requirements.txt
- tests/ui/explorer/test_explorer.py
- wetterdienst/ui/explorer/app.py
- wetterdienst/ui/explorer/layout/main.py
- wetterdienst/ui/explorer/layout/observations_germany.py
- wetterdienst/ui/explorer/library.py
With #503, we added a provider adapter for NOAA GHCN. This patch adjusts Wetterdienst Explorer accordingly, in order to be able to select both `provider` and `network` as new parameters.
> Update wetterdienst explorer to leverage all APIs

- docs/usage/cli.rst
- outdated examples are updated for the case of provider dwd and network mosmix which previously was named forecast
> Update examples to use network mosmix instead of forecast for provider dwd

- THIRD_PARTY_NOTICES
- poetry.lock
- requirements.txt
- tests/ui/explorer/test_explorer.py
- wetterdienst/provider/dwd/mosmix/api.py
- wetterdienst/ui/core.py
- wetterdienst/ui/explorer/app.py
The special case of DWD Mosmix which has no resolution but rather mosmix type was not taken into account by wetterdienst explorer. This PR fixes the issue and adds a test for the case.
Fixes #593
> Fix explorer to work with DWD Mosmix

- .github/workflows/tests.yml
- CHANGELOG.rst
- README.rst
- THIRD_PARTY_NOTICES
- poetry.lock
- pyproject.toml
- requirements.txt
- tests/provider/dwd/observation/test_api_data.py
- tests/provider/dwd/test_util.py
- tests/ui/explorer/test_explorer.py
- wetterdienst/__init__.py
- wetterdienst/core/scalar/export.py
Python 3.10 is added to supported version and Python 3.7 is dropped. In terms of dependencies drop crate temporarily as of its requirements for sqlalchemy < 1.4 while pandas requires sqlalchemy >= 1.4
> Add support for Python 3.10 and drop Python 3.7

- CHANGELOG.rst
- tests/core/scalar/test_parameter.py
- wetterdienst/provider/eccc/observation/metadata/parameter.py
- wetterdienst/provider/noaa/ghcn/api.py
We've recently seen problems with our enumerations at #608 due to changing of names of datasets which were not entirely captured within all instances that should use those dataset names. The newly added tests should capture such errors.
> Add tests to improve integrity of dataset, parameter and unit enums

- .github/release/full/Dockerfile
- .github/release/standard/Dockerfile
This PR reduces the size of the standard and full docker image
* Remove `sql` and `duckdb` for now since it causes problems
* Reduce the image size by removing apt/pip caches
* Removing `git` as it is not needed
Using Python 3.8.8 image both standard and full build fine on amd64 but crash on arm64.
I tried to update Python 3.8.8 to the newest Python 3.8 or Python 3.9 version which also changes the Debian version from 10 (buster) to 11 (bullseye). The following apt adjustments are needed then:
* Changing `libmariadbclient-dev` to `libmariadb-dev`
* `libgdal20` to `libgdal28`
Unfortunately the pip installation of gdal crahes then.
> Optimize Docker images

- CHANGELOG.rst
- poetry.lock
- tests/provider/dwd/radar/test_api_historic.py
- wetterdienst/provider/dwd/radar/access.py
Dear all,
previously historical DWD radolan data was mistakenly extracted only as one file which would match the start date of the request however the historical data includes multiple files per archive where for each of them we have to check if their timestamp lays in between our search space - start date and end date. This PR slightly adjusts the radar acquisition to return multiple files depending on the date range that is provided within the radar request.
Downside:
Atm when working with the TarFIleSystem from fsspec, each time a file is opened from the archive like
```python
from fsspec.implementations.tar import TarFileSystem
tfs = TarFileSystem(archive_in_bytes, compression="gzip")
file_in_bytes = tfs.open("file_for_date_x").read()
```
after reading the file it is closed and we can …
> Fix radar acquisition from archives for historical DWD radolan data

- CHANGELOG.rst
- wetterdienst/provider/eccc/observation/api.py
- wetterdienst/provider/eccc/observation/metadata/resolution.py
The class `EcccObservationResolution` is missing a `c`.
> Fix EcccObservationResolution typo

- .github/workflows/tests.yml
- CHANGELOG.rst
- docs/usage/python-api.rst
- poetry.lock
- tests/core/scalar/test_api.py
- wetterdienst/core/scalar/request.py
- wetterdienst/core/scalar/result.py
- wetterdienst/core/scalar/values.py
- wetterdienst/settings.py
- wetterdienst/ui/cli.py
- wetterdienst/ui/core.py
- wetterdienst/ui/explorer/app.py
- wetterdienst/ui/restapi.py
Dear all,
this PR adds two options to wetterdienst:
- `skip_empty`can be used to skip stations whose values are empty according to a given threshold `skip_threshold? which is defaulted to 95% meaning a station is seen as empty if of each parameter requested the values have less then 95 % actual values
- `dropna` can be used to drop values which are NaN from the returned values DataFrame
Cheers
Benjamin
> Add options for handling missing data

- CHANGELOG.rst
- pyproject.toml
- tests/provider/dwd/observation/test_available_datasets.py
- wetterdienst/provider/dwd/observation/metadata/dataset.py
Dear all,
we have a solid enumeration base for the datasets provided by DWD observations. However from time to time they may release new datasets which are obviously at this moment not covered by wetterdienst. Therefor this PR installs a test to compare actually provided DWD observation datasets with the ones we made available with wetterdienst.
Also this test has uncovered that wind_extreme dataset was missing in one place of our DWD observations resolution-dataset-mapping. This was added at the required place.
Cheers
Benjamin
> Add test for comparing actual DWD observation datasets with the ones of wetterdienst

- CHANGELOG.rst
- pyproject.toml
- tests/provider/dwd/observation/test_api_data.py
- tests/ui/test_restapi.py
- wetterdienst/provider/dwd/observation/metadata/dataset.py
Dear all,
after @pedroalencar1 has handed in an issue requesting daily solar data of DWD observations I spotted a mistake in our dwd observation period mapping. This has been figured out correctly for hourly solar data however for the daily dataset the mapping did only contain period recent and not period historical which would also account for the provided data.
After adding the period to the mapping everything works as expected. I also added a test for this scenario.
Cheers
Benjamin
Fixes #690
> Fix access of DWD observation solar daily data

- CHANGELOG.rst
- docs/usage/python-api.rst
- poetry.lock
- pyproject.toml
- tests/provider/dwd/observation/test_available_datasets.py
- tests/test_settings.py
- wetterdienst/__init__.py
- wetterdienst/settings.py
- wetterdienst/util/cache.py
- wetterdienst/util/network.py
Dear all,
this PR moves the cache settings to the global wetterdienst Settings object. I am currently not happy with the situation around the `cache_disable` attribute, which should have an initial printout so that the user knows if the cache is disabled but also throughout enabling/disabling again inform the user about the current mode of cache.
Apparently using a property on a dataclass field is quite complicated however the thread at [1] had a working solution.
@amotl Do you have any suggestions on this?
Cheers
Benjamin
[1] https://florimond.dev/en/posts/2018/10/reconciling-dataclasses-and-properties-in-python/
> Move cache settings

- CHANGELOG.rst
- wetterdienst/metadata/parameter.py
Parameters `VISIBILITY_RANGE` and `PROBABILITY_VISIBILITY_BELOW_1000_M` had wrong values. Although this shouldn't be of a big deal, they should follow the general mapping scheme.
> Fix two parameter names

- CHANGELOG.rst
- wetterdienst/core/scalar/values.py
- wetterdienst/provider/eccc/observation/api.py
- wetterdienst/util/network.py
Dear all,
this is to satisfy linters and adjust some smaller code blocks accordingly. Previously for the conversion of units a local-global variable was created from which the conversion function drew its factors and operands. Now this object is passed directly to the function to clarify the use.
Few other small changes were done, where previously certain objects were created but not used.
Fixes #713
> Cleanup some code blocks

- .github/release/full/Dockerfile
- .github/release/standard/Dockerfile
- .github/workflows/install.sh
- CHANGELOG.rst
- poetry.lock
Previously at another PR #719 the docker images could not be build because of some errors with cartopy. This PR fixes these issues updating to a newer python version and ensuring cartopy 0.21.0.
> Fix docker images

- CHANGELOG.rst
- tests/test_settings.py
- wetterdienst/provider/noaa/ghcn/api.py
Latest tests have shown that NCEI sources for NOAA GHCN are not stable/available. This PR changes the sources to AWS base to improve availability.
> Change NOAA GHCN source to AWS

- CHANGELOG.rst
- tests/ui/test_cli.py
- tests/ui/test_restapi.py
- wetterdienst/provider/eccc/observation/api.py
- wetterdienst/provider/noaa/ghcn/api.py
- wetterdienst/provider/wsv/pegel/api.py
The explorer previously didn't work for some weather services which had a fixed period and for which we set an instance as period base rather than an enum with a single value. Now with an enum class set as period base they work once again.
Also for ECCC Observation the date range was previously set to loosely which would require setting start date and end date. However the data provided actually is given in chunked files and setting was changed to date range fixed. This now also works once again.
> Make explorer work again

- .github/workflows/coverage.yml
- .github/workflows/docker-publish-full.yml
- .github/workflows/docker-publish-standard.yml
- .github/workflows/docs.yml
- .github/workflows/linter.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- tests/provider/dwd/radar/test_api_current.py
- tests/provider/dwd/radar/test_api_historic.py
- tests/provider/dwd/radar/test_api_most_recent.py
This patch is another stab at #730. `actions/setup-python@v4` already implements caching for dependencies, so we can get rid of `actions/cache@v2`. Even if it might increase runtime, I think a _stable_ test harness is more important.
- Beforehand: ~12-30 minutes total runtime, with ~5-13 minutes runtime per test matrix slot. [1]
- On the change: 24 minutes total runtime, with 9-23 minutes total runtime per test matrix slot, 2-4 minutes for installing the project dependencies. Caches ~250-325 MB worth of data. [2]
- Subsequent run [^1]: 19 minutes total runtime, with 7-13 minutes total runtime per test matrix slot on Linux/macOS and 13-18 minutes on Windows. 15-45 seconds for setting up Python including cached dependencies, 0 seconds for _installing_ the project dependencies.
[1] …
> CI: Modernize GHA action recipes and fix dependency caching issue

- tests/provider/dwd/radar/test_api_historic.py
- tests/provider/dwd/radar/test_api_latest.py
- tests/provider/dwd/radar/test_api_most_recent.py
Skip corresponding tests when `wradlib` is not installed. This fixes #734 on my machine and will make parts of the test suite easier to run, specifically for all people who observe similar problems when having `wradlib` installed.
> Tests: Do not strongly depend on `wradlib`

- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- tests/provider/dwd/radar/test_api_recent.py
Even after #733, tests on CI still have been weirdly flaky, see [1,2]. It looks like the package `webdriver-manager` is not getting installed properly.
```
pytest -vvv --numprocesses=auto -m not (explorer or cflake) tests
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --webdriver=Firefox --headless
```
**Always** running the _Install project_ step will add another 15-20 seconds per test matrix slot, but it will be much safer.
Total test suite runtime on CI: 15-18 minutes. See [3,4].
[1] https://github.com/earthobservations/wetterdienst/actions/runs/3127778053
[2] https://github.com/earthobservations/wetterdienst/actions/runs/3127794985
[3] https://github.com/earthobservations/wetterdienst/actions/runs/3127931982
[4] …
> CI: Never skip installing dependencies

- .gitignore
- example/radar/radar_radolan_cdc.py
- example/radar/radar_radolan_rw.py
- example/radar/radar_site_dx.py
- poetry.lock
- pyproject.toml
- tests/provider/dwd/radar/test_api_historic.py
- tests/provider/dwd/radar/test_api_most_recent.py
- tests/provider/dwd/radar/test_api_recent.py
- wetterdienst/core/scalar/export.py
- wetterdienst/core/scalar/values.py
- wetterdienst/provider/dwd/mosmix/api.py
- wetterdienst/provider/dwd/radar/metadata/parameter.py
- wetterdienst/provider/dwd/radar/sites.py
- wetterdienst/provider/wsv/pegel/api.py
- wetterdienst/ui/cli.py
- wetterdienst/ui/restapi.py
[`ruff`](https://github.com/charliermarsh/ruff) is an extremely fast Python linter, written in Rust by @charliermarsh. Working with it is a true pleasure.
```
$ time poe turbolint
Poe => ruff wetterdienst example tests
real	0m0.128s
user	0m0.105s
sys	0m0.051s
```
https://github.com/earthobservations/wetterdienst/blob/0e7332b54ac91d51fb4441eea2383f7bfc3b2320/pyproject.toml#L286-L294
@Seamooo: Your recent improvement to add the `per-file-ignores` option with https://github.com/charliermarsh/ruff/pull/261 arrived just in time. Thank you.
> QA: Add `ruff` linter. Invoke with `poe turbolint`.

- CHANGELOG.rst
- tests/provider/dwd/observation/test_api_data.py
- tests/provider/dwd/radar/test_api_current.py
- tests/provider/dwd/radar/test_api_most_recent.py
- tests/provider/dwd/radar/test_api_recent.py
- wetterdienst/core/scalar/values.py
- wetterdienst/provider/dwd/observation/api.py
At #754 @TheAnalystx has seen an error with empty data. Originally when converting units and the passed dataframe was empty, a new empty dataframe without any specifications was returned. This PR changes the behaviour to just pass the original dataframe with existing columns if the dataframe is empty so to prevent the returning of an completely empty dataframe.
> Fix passing an empty DataFrame through unit conversion

- CHANGELOG.rst
- docs/usage/python-api.rst
- example/mosmix_forecasts.py
- tests/provider/dwd/radar/test_api_historic.py
- wetterdienst/provider/dwd/metadata/constants.py
- wetterdienst/provider/dwd/mosmix/api.py
DWD Mosmix-L all stations is finally back and apparently with the new stream parser it works as fluent as it could.
Fixes #586
> Add support for reading DWD Mosmix-L all stations files

- CHANGELOG.rst
- wetterdienst/core/scalar/values.py
Dear all,
apparently there was a bug with dropping duplicates of acquired data. The duplicates where detected only based on the date column however this would cause a dataset with multiple parameters to return only data for the first appearing parameter with this date. 
Now data is dropped according to all columns.
Cheers,
Benjamin
> Fix bug with dropping duplicates of acquired data

- wetterdienst/provider/nws/observation/api.py
Coming from https://github.com/earthobservations/wetterdienst/pull/781#discussion_r1027381956, this is hopefully a minor, but sensible improvement. Please let me know if you think it's not.
> NWS API: Adjust `User-Agent` header

- poetry.lock
- pyproject.toml
- Improve `per-file-ignore` configuration for ruff linter
- Update ruff linter to version 0.0.135
> Improve `ruff` configuration

- CHANGELOG.rst
- wetterdienst/core/scalar/interpolate.py
Dear all,
beforehand when using `interpolate/summarize`, we were not able to query an existing station because it would not lay INSIDE one of the station group polygons:
https://github.com/earthobservations/wetterdienst/blob/d54e0f0c19758e15829aac6bb606b4151b3c62e2/wetterdienst/core/scalar/interpolate.py#L161
With this small change now an existing station location can be queried. This will allow us (in a further step) to simply take those stations values instead of interpolating/summarizing and ONLY interpolate/summarize where this station has no values.
Basically with the current workflow of `summarize` this is already happening because the nearest station would be the one the values are taken from but for `interpolate` we will have to do some approximation like `distance < 500m` to …
> Allow querying an existing station via interpolate/summarize

- CHANGELOG.rst
- benchmarks/interpolation.py
- benchmarks/interpolation_over_time.py
- benchmarks/interpolation_precipitation_difference.py
- docs/usage/python-api.rst
- example/observations_stations.py
- tests/core/scalar/test_api.py
- tests/core/scalar/test_interpolation.py
- tests/core/scalar/test_summary.py
- tests/provider/dwd/mosmix/test_api_data.py
- tests/provider/dwd/observation/test_api_data.py
- tests/provider/dwd/observation/test_api_stations_geo.py
- wetterdienst/core/scalar/interpolate.py
- wetterdienst/core/scalar/request.py
- wetterdienst/core/scalar/summarize.py
- wetterdienst/ui/core.py
Dear all,
this changes the function signatures where we query points (latitude, longitude) to use a latlon tuple instead.
This makes it easier to handle alternative input.
Especially we plan to let the user ask for summary/interpolation for an already given station id, assuming that its data is not complete.
> Change geo function signature 

- poetry.lock
- pyproject.toml
Hi,
@xylar recommended at https://github.com/conda-forge/wetterdienst-feedstock/pull/76#issuecomment-1330346041:
> One thing you could do there to make things easier here would be to alphabetize the dependencies (other than python, which should stay at the top). That is a pretty standard practice for python packages.
This patch implements his suggestion. Thank you very much.
Andreas.
> Chore: Sort dependency packages in pyproject.toml

- poetry.lock
- pyproject.toml
Apparently, `eccodes` and `pdbufr` are used no where in the code, so let's remove them from the project metadata.
Reference:
- #813
/cc @xylar
> Chore: Remove `eccodes` and `pdbufr` dependencies

- CHANGELOG.rst
- docs/usage/python-api.rst
- tests/core/scalar/test_interpolation.py
- tests/core/scalar/test_summary.py
- wetterdienst/core/scalar/interpolate.py
- wetterdienst/core/scalar/request.py
- wetterdienst/core/scalar/tools.py
- wetterdienst/exceptions.py
Dear all,
this PR enables us to query for a already given station within the setting of `.interpolate` and `.summarize`.
We often have users that want values for a specific station but then realize that the station has actually no values for their specified date range. The users can now simply submit their station id but within the given methods to receive a more complete dataset.
Instead of 
```python
request = Request(...).filter_by_station_id("1048")
```
one can now call
```python
request = Request(...).summarize_by_station_id("1048")
```
which will automatically fill in values from neighbouring stations where 1048 has no values.
> Enable querying station id instead of latlon in interpolate/summary

- CHANGELOG.rst
- tests/core/scalar/test_interpolation.py
- tests/test_api.py
- wetterdienst/core/scalar/interpolate.py
- wetterdienst/core/scalar/request.py
- wetterdienst/core/scalar/summarize.py
- wetterdienst/core/scalar/tools.py
- wetterdienst/settings.py
Dear all,
with this PR the interpolation now uses the existing station values if there are nearby stations instead of interpolating the values from surrounding stations.
I set the default to 1 (km) meaning the nearby station should be 1km distant from the latlon tuple to be used instead of interpolation. This could as well mean that if a city has two stations close to each other, it would simply take values of the other station. If the limit is reduced to something like 100 to 200 m it would probably only rely on the one station of favor, because stations should not move that far (if even move after all).
I changed an existing test to rather "jump" on another station which has a shorter history in values and also has more stations around it with comparatively longer history. This makes it …
> Allow using values of nearby stations instead of interpolated values if available

- pyproject.toml
@gutzbenj mentioned at https://github.com/earthobservations/wetterdienst/issues/813#issuecomment-1340461199:
> Currently, there's two times `dash` in the `pyproject.toml`, one for testing and one for production, both with different versions pinned.
This patch fixes this anomaly.
> Dependencies: Use Dash 2.x everywhere

- tests/provider/dwd/radar/test_api_latest.py
- tests/ui/test_cli.py
- tests/util/test_url.py
This patch may improve the situation when running the test suite in parallel with `pytest-xdist`, where a test case may otherwise try to access the same resource concurrently. Closes #739.
> Tests: Improve tests wrt. temporary file creation

- .github/workflows/tests.yml
- tests/provider/dwd/observation/test_io.py
In order to speed up test execution on CI, let's also use `pytest-xdist` for running the test suite on Windows.
When running the tests in parallel with `pytest-xdist`, using `poe test-parallel`, it croaks on Windows.
> CI: Use `pytest-xdist` for Windows on GHA

- CHANGELOG.rst
- wetterdienst/core/scalar/summarize.py
- wetterdienst/core/scalar/tools.py
Dear all,
the same problem we've seen with numeric column names at the interpolation/summary DataFrame appears in the method gain_of_value_pairs. We can circumvent the problem by adding any character at the beginning e.g. S000001.
Cheers,
Benjamin
> Fix error with numeric column names in method gain_of_value_pairs

- CITATION.cff
- poetry.lock
- pyproject.toml
- tools/citation.py
- wetterdienst/core/scalar/request.py
This adds
- CITATION.cff
- small script to generate it
- poe command to run generation
Notice: release date is not parsed from changelog (possible source) but just set to current date
> Add CITATION.cff 

- wetterdienst/api.py
- wetterdienst/core/scalar/request.py
- wetterdienst/ui/cli.py
- wetterdienst/ui/core.py
- wetterdienst/ui/explorer/app.py
- wetterdienst/ui/explorer/layout/observations_germany.py
- wetterdienst/util/parameter.py
- wetterdienst/util/python.py
This patch intends to improve startup speed and memory use, see GH-791.
The `RequestRegistry` (ex. `ApiEndpoints`) class now provides their members lazily. While the implementation is not optimal, it does not break its interface too much. Access to its internals is encapsulated using appropriate methods now (`discover`, `resolve`, `get_provider_names`, `get_network_names`), to make subsequent refactoring easier.
Other than this, a few other modules will now only be loaded at runtime when they are actually needed.
```
$ time python -c 'import wetterdienst'
real	0m3.111s
user	0m3.962s
sys	0m0.773s
```
```
$ time python -c 'import wetterdienst'
real	0m0.633s
user	0m1.200s
sys	0m0.253s
```
> Defer module loading to improve startup speed and memory use

- .github/release/full/Dockerfile
- .github/release/selftest.sh
- .github/release/standard/Dockerfile
I recently discovered that the Docker builds are succeeding, even if `selftest.sh` fails. This PR exists to exercise the situation.
```
Step 7/7 : COPY .github/release/selftest.sh /usr/local/bin
---> c85a81956fa1
Successfully built c85a81956fa1
Successfully tagged release_sut:latest
Creating release_sut_run ... 
Creating release_sut_run ... done
/usr/local/bin/selftest.sh: line 6: foobar: command not found
Testing wetterdienst
Usage: wetterdienst [OPTIONS] COMMAND [ARGS]...
Try 'wetterdienst --help' for help.
Error: No such option: --version
Usage: wetterdienst [OPTIONS] COMMAND [ARGS]...
Try 'wetterdienst --help' for help.
Error: No such command 'dwd'.
```
-- https://github.com/earthobservations/wetterdienst/actions/runs/3976322659/jobs/6816730928#step:6:292
Despite this is clearly …
> Modernize Docker environments, and fix erroneous `selftest.sh` not failing the Docker SuT procedure

- .github/release/full/Dockerfile
- .github/workflows/docker-publish-full.yml
- .github/workflows/docker-publish-standard.yml
- .github/workflows/install.sh
Just for testing, this brings in the patch from GH-872, but from within the same repository. Over there, we are observing a lack of permissions when GHA attempts to push the PR-based image to GHCR. This is a detail we did not do before, where we skipped pushing on PR builds.
/cc @neumann-nico
> CI: Modernize GHA Docker build & publish recipe

- .github/dependabot.yml
Currently we only search for Python updates periodically.
This PR lets dependabot search for Github Action updates monthly.
This make it easier than manually searching for updates.
> Let dependabot search for Github Action updates monthly

- .github/workflows/dependency-review.yml
- .github/workflows/docker-publish-full.yml
- .github/workflows/docker-publish-standard.yml
Updates all Github Actions to the latest version.
This is a combination of all dependabot PRs to avoid running the CI tests multiple times after merging.
> Update GitHub actions

- .github/release/full/Dockerfile
- .github/release/selftest.sh
- .github/workflows/install.sh
- README.rst
- docs/usage/docker.rst
- example/radar/radar_composite_rw.py
- example/radar/radar_radolan_cdc.py
- example/radar/radar_radolan_rw.py
- example/radar/radar_scan_precip.py
- example/radar/radar_scan_volume.py
- example/radar/radar_site_dx.py
- example/radar/radar_sweep_hdf5.py
- pyproject.toml
- tests/example/test_regular_examples.py
This is a followup to GH-878, improving the setup of wradlib and h5py, and finally resolving the GDAL gordian-knot for Python>=3.9.
> CI: Improve installation of `wradlib` and `h5py`. Remove dependency on GDAL.

- example/radar/radar_scan_precip.py
- example/radar/radar_scan_volume.py
This adapts the radar examples to build on xradar/datatree instead of wradlib.
This is the recommended way of ingesting radar files. Currently there is only a shallow compatibility layer remaining in wradlib, which will be removed in wradlib 2.0.
There is still some convenience functionality missing. But the decision was to put not too much magic into xradar and leave it to the users to handle specifics of their data.
> new radar examples building on xradar

- .github/release/full/Dockerfile
- .github/release/standard/Dockerfile
- .github/workflows/docker-publish-full.yml
- .github/workflows/docker-publish-standard.yml
- docs/contribution/development.rst
GH-904 will need a compiler toolchain to be installed, because the newly introduced dependency `backports-datetime-fromisoformat` requires it, as it does not ship as a wheel package.
So, while adding `build-essential` to the `standard/Dockerfile` variant, I took the chance to modernize the Dockerfiles a bit, and align them to the ones I am using at [mqttwarn](https://github.com/jpmens/mqttwarn).
> Packaging: Improve Dockerfiles for OCI image building

- .github/release/full/Dockerfile
- .github/release/standard/Dockerfile
It looks like the main intention of GH-933, to add `python3-dev`, got lost somehow. Apologies.
> Packaging: Finally add `python3-dev` to OCI image building

- wetterdienst/metadata/unit.py
This was previously misdefined, which leads to wrongly scaled values at least for the DWD MOSMIX prognoses.
> Fix JOULE_PER_SQUARE_METER definition from kilojoule/m2 to joule/m2

- wetterdienst/metadata/unit.py
- wetterdienst/provider/dwd/mosmix/metadata/unit.py
Follow-up to #937
According to the DWD definition (https://opendata.dwd.de/weather/lib/MetElementDefinition.xml), the rad1h (RADIATION_GLOBAL) is expressed as kJ/m2, not as a percentage value. Or am I misunderstanding something here?
> Fix Unit definition for RADIATION_GLOBAL

- README.rst
I had missed this to not be the regular readme markdown. Now the links are correctly displayed as I had intended. Sorry for not taking a Preview...
> rdwd link format corrected

- .github/release/standard/Dockerfile
Upgrades Docker image from Debian 11 bullseye to Debian 12 bookworm for the standard Dockerfile.
The full Dockerfile is already upgraded to Debian 12, see https://github.com/earthobservations/wetterdienst/blob/main/.github/release/full/Dockerfile#L1
> Upgrade Debian version to 12 bookworm

- CHANGELOG.rst
- README.rst
Coming from https://github.com/earthobservations/wetterdienst/issues/963#issuecomment-1600860383, this patch aims to update the change log correspondingly, that some user-space code heavily using pandas idioms may need updates after the migration to Polars.
> Retroactively update change log about breaking change with Polars

- .github/workflows/docker-publish-full.yml
- .github/workflows/docker-publish-standard.yml
The OCI image build machinery can't upload to GHCR when running on behalf of non-members.
_Thanks for outlining this idea on behalf of GH-950 already. I think this update actually makes it work as intended._
- https://github.com/panodata/grafana-wtf/pull/71
- https://github.com/daq-tools/lorrystream/pull/19
> CI: Do not build and publish OCI images on GHA PRs from non-members

- CHANGELOG.rst
- docs/data/coverage/geosphere/observation/daily.rst
- docs/data/coverage/geosphere/observation/hourly.rst
- docs/data/coverage/geosphere/observation/minute_10.rst
- docs/data/coverage/geosphere/observation/monthly.rst
- tests/provider/geosphere/observation/test_api.py
- wetterdienst/provider/geosphere/observation/api.py
Dear @mhuber89,
this patch should accommodate the needs to fix the documentation as well as unit conversion mentioned in #988 .
To ensure the right conversion factor I looked it up here: https://hextobinary.com/unit/heatflux/from/wpm2/to/jsm2
Please check the changes and comment below!
> Fix documentation and unit conversion for Geosphere 10minute radiation data

- poetry.lock
- pyproject.toml
More version bumps, related to GH-1015, following up on GH-1017 and GH-1018.
> Dependencies: Bump leftover versions using version range constraints

- .github/dependabot.yml
- .github/workflows/tests.yml
@kmuehlbauer reported dependency staleness at GH-1015. Thanks. It turned out that Dependabot only bumped versions in `poetry.lock`. That's not enough.
**Please do not merge** before we updated the dependencies manually, en bloc. Otherwise, it will probably spawn hundreds of PRs ;].
> CI: Fix Dependabot configuration

- .github/workflows/install.sh
- poetry.lock
- pyproject.toml
Percy should actually be pulled in appropriately by `dash[testing]`, right? So, it should do no harm removing the direct dependency to `percy-selenium` here. CI may prove me wrong ;].
> Dependencies: Remove Percy

- poetry.lock
- pyproject.toml
There are lots of flukes when running the whole test suite, because, well, some data source is always intermittently down or is currently being populated at the time of being accessed, tripping one or another test case. See also GH-816 for a few samples we collected.
This patch intends to retry flaky tests, thereby improving the consistency of the test suite results, mostly for the scenarios outlined above. It obviously does not help if the data source is completely down, or unavailable/wrong/corrupt for a longer amount of time.
> Tests: Re-run test cases on failures

- tests/ui/test_restapi.py
May fix/improve https://github.com/earthobservations/wetterdienst/issues/816#issuecomment-1745473729, or not.
> Three failures of `test_api_values_missing_null` in two different PRs, GH-1038 and GH-1040, and when merging GH-1041 into the `main` branch, apparently only happening on Windows.
> Tests: Mark test case `test_api_values_missing_null` as `cflake`

- .readthedocs.yml
May fix an error at an RTD build, on behalf of GH-1026, see https://readthedocs.org/projects/wetterdienst/builds/22113003/, or not.
https://readthedocs.org/projects/wetterdienst/builds/22113221/
> Read the Docs: Use Python 3.11

- CHANGELOG.rst
- docs/usage/cli.rst
- tests/core/timeseries/test_io.py
- tests/provider/dwd/observation/test_api_stations.py
- tests/provider/dwd/road/test_data.py
- tests/ui/cli/conftest.py
- tests/ui/cli/test_cli.py
- tests/ui/cli/test_cli_stations.py
- tests/ui/cli/test_cli_values.py
- tests/ui/test_restapi.py
- wetterdienst/core/timeseries/export.py
- wetterdienst/core/timeseries/request.py
- wetterdienst/core/timeseries/result.py
- wetterdienst/ui/cli.py
- wetterdienst/ui/core.py
- wetterdienst/ui/restapi.py
This PR adds 
- a common format for dict like exports with fixed keys `metadata`, `stations` and `values`
- extensive typing for dict like exports
- ogc/geojson export support for values/interpolation/summary
Also tests for the cli are split up due to the amount of code.
> Rework export formats and tests

- .github/workflows/tests.yml
- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- tests/core/timeseries/test_io.py
- tests/example/test_notebook_examples.py
- tests/example/test_regular_examples.py
- tests/ui/test_restapi.py
Trying to bring in support for Python 3.12, ~~to be~~ released on 2023-10-02 [^1].
NumPy compatibility for Python 3.12 (https://github.com/numpy/numpy/issues/23808) is probably only one step-stone towards Python 3.12. ~The build will probably fail due to various other reasons.~
[^1]: https://devguide.python.org/versions/
> CI: Add support for Python 3.12

- pyproject.toml
The upper bound breaks installs of dependees, while providing no maintainance benefit. See: https://github.com/roboflow/supervision/pull/658
> Remove Python version upper bound

- pyproject.toml
The optional `pdbufr` dependency specifies that it needs an `eccodes` extra but this is not defined.  Presumaly the `eccodes` extra is just the `eccodes` package, as I have defined it here. However, it doesn't seem this happens automatically and it seems the fact that the `eccodes` extra was not defined somehow caused `eccodes` to become a required, rather than an optional, dependency.  With this fix, `pip check` passes in an environment with `wetterdienst` and without `eccodes`.  See:
https://github.com/conda-forge/wetterdienst-feedstock/pull/118
> Define missing `eccodes` extra

- .github/release/full/Dockerfile
- .github/release/standard/Dockerfile
- CHANGELOG.rst
We can reduce the image size by only taking the parts that we need for the final stage.
Tested on linux/amd64 platform:
* Standard: 447MB -> 299MB
* Full: 677Mb -> 385MB
> Reduce docker image size by using multi stage

- .github/workflows/tests.yml
> January 30, 2024
>
> GitHub announced the launch of the new M1 macOS runner. It provides 3 vCPU, 7 GB RAM, and 14 GB of storage VM, and the latest Mac hardware Actions has to offer. The new runner operates exclusively on macOS 14 and to use it, simply update the runs-on key in your YAML workflow file to `macos-14`.
- https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
- https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md
- https://github.com/actions/runner-images/issues/7508
- https://github.com/actions/runner-images/issues/9254
- https://github.com/containerbase/base/issues/2084
> CI: Run software tests on GHA/macOS/M1

- wetterdienst/provider/dwd/observation/parser.py
Make docstring match typehints.
I am working with the DWD at work and we've written our own parser (though much less sophisticated). 
Stumbling upon this project, it looks very promising (I wasn't even aware of Polars before!). :)
I read through some of the code to understand what the library is doing, and I noticed that the docstring didn't match the actual function typehints (Did you change from pandas -> polars at some point?)
There might be more documentation where this is the case.
If there is a misunderstanding on my end, please let me know.
Thanks for the work you've put into this! <3
> docstring doesn't match method signature

- wetterdienst/monkeypatch/fsspec_monkeypatch.py
The monkeypatching done for `AsyncFileSystem` currently breaks 3rd party `AsyncFileSystem` because it doesn't use cooperative inheritance, so not `__init__`s in a classes MRO are called when subclassing `AsyncFileSystem`, breaking filesystems like [adlfs](https://github.com/fsspec/adlfs).
This PR fixes that by adding the missing `super().__init__` call.
> Fix `AsyncFileSystem` monkeypatching breaking 3rd-party file systems

- setup.py
This reverts commit 8703eb9d9e76e012c5e2ebeafcca7248057fbe3e.
A surrogate `setup.py` is needed to enable the "Used by" section on GitHub. GitHub apparently still can't decode projects exclusively using `pyproject.toml` files in 2024.
- GH-800
> Revert "Remove unnecessary setup.py"

- wetterdienst/provider/dwd/observation/api.py
Avoid type error messages when assigning lists that contain just one single datatype.
As [discussed here](https://github.com/DetachHead/basedpyright/issues/534), type checkers raise an error when a list of type `list[str]` or any other list with just one datatype is assigned to a parameter with the type `list[str | DwdObservationDataset | DwdObservationParameter]`
> Use Sequence as type hint

- CHANGELOG.rst
- examples/provider/dwd/road/dwd_road_validation.py
- tests/provider/dwd/road/test_api.py
- wetterdienst/provider/dwd/road/api.py
The DWD has added new road weather station groups, which are synced with this commit. Also, for some station groups, theres apparently no data. This is now being logged if no particular files are found for a station.
> DWD Road: Add new station groups

- .github/workflows/codeql.yml
- .github/workflows/coverage.yml
- .github/workflows/docker-publish.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
Drop the `uv python pin` block as well as `enable-cache` parameter which now defaults to true.
> Bump astral-sh/setup-uv from 4 to 5

- CHANGELOG.md
- docs/usage/python-api.md
- docs/usage/restapi.md
- examples/provider/dwd/observation/dwd_obs_stations_filter_by_examples.py
- examples/provider/dwd/observation/dwd_obs_values_sql.py
- tests/core/timeseries/test_io.py
- tests/ui/test_restapi.py
- wetterdienst/core/timeseries/export.py
- wetterdienst/core/timeseries/request.py
- wetterdienst/ui/cli.py
This PR changes the SQL syntax we are using to `duckdb.sql` which queries the local scope data. This way we do not need the round trip with pandas. Also, we are now only asking for the WHERE clause e.g. `"parameter='precipitation_height'"`.
> Use duckdb.sql and ask only for WHERE clause

- tests/core/timeseries/test_request.py
This small PR resolves the Polars deprecation warnings, which you can find in the [CI logs](https://github.com/earthobservations/wetterdienst/actions/runs/15287578226/job/43000924825):
```python
/Users/runner/work/wetterdienst/wetterdienst/tests/core/timeseries/test_request.py:354: DeprecationWarning: `GroupBy.count` is deprecated. It has been renamed to `len`.
```
> Use updated Polars API for row counting in grouped DataFrames
